// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/enhanced_types.proto

package com.google.cloud.aiplatform.v1beta1;

public final class EnhancedTypesProto {
  private EnhancedTypesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_aiplatform_v1beta1_TrainingJobDefinition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_TrainingJobDefinition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_aiplatform_v1beta1_PredictInstances_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_PredictInstances_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_PredictParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_aiplatform_v1beta1_PredictionResults_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_PredictionResults_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4google/cloud/aiplatform/v1beta1/enhanc" +
      "ed_types.proto\022\037google.cloud.aiplatform." +
      "v1beta1\032Rgoogle/cloud/aiplatform/v1beta1" +
      "/schema/predict/instance/image_classific" +
      "ation.proto\032Tgoogle/cloud/aiplatform/v1b" +
      "eta1/schema/predict/instance/image_objec" +
      "t_detection.proto\032Pgoogle/cloud/aiplatfo" +
      "rm/v1beta1/schema/predict/instance/image" +
      "_segmentation.proto\032Qgoogle/cloud/aiplat" +
      "form/v1beta1/schema/predict/instance/tex" +
      "t_classification.proto\032Mgoogle/cloud/aip" +
      "latform/v1beta1/schema/predict/instance/" +
      "text_extraction.proto\032Lgoogle/cloud/aipl" +
      "atform/v1beta1/schema/predict/instance/t" +
      "ext_sentiment.proto\032Vgoogle/cloud/aiplat" +
      "form/v1beta1/schema/predict/instance/vid" +
      "eo_action_recognition.proto\032Rgoogle/clou" +
      "d/aiplatform/v1beta1/schema/predict/inst" +
      "ance/video_classification.proto\032Sgoogle/" +
      "cloud/aiplatform/v1beta1/schema/predict/" +
      "instance/video_object_tracking.proto\032Pgo" +
      "ogle/cloud/aiplatform/v1beta1/schema/pre" +
      "dict/params/image_classification.proto\032R" +
      "google/cloud/aiplatform/v1beta1/schema/p" +
      "redict/params/image_object_detection.pro" +
      "to\032Ngoogle/cloud/aiplatform/v1beta1/sche" +
      "ma/predict/params/image_segmentation.pro" +
      "to\032Tgoogle/cloud/aiplatform/v1beta1/sche" +
      "ma/predict/params/video_action_recogniti" +
      "on.proto\032Pgoogle/cloud/aiplatform/v1beta" +
      "1/schema/predict/params/video_classifica" +
      "tion.proto\032Qgoogle/cloud/aiplatform/v1be" +
      "ta1/schema/predict/params/video_object_t" +
      "racking.proto\032Ngoogle/cloud/aiplatform/v" +
      "1beta1/schema/predict/prediction/classif" +
      "ication.proto\032Vgoogle/cloud/aiplatform/v" +
      "1beta1/schema/predict/prediction/image_o" +
      "bject_detection.proto\032Rgoogle/cloud/aipl" +
      "atform/v1beta1/schema/predict/prediction" +
      "/image_segmentation.proto\032Vgoogle/cloud/" +
      "aiplatform/v1beta1/schema/predict/predic" +
      "tion/tabular_classification.proto\032Rgoogl" +
      "e/cloud/aiplatform/v1beta1/schema/predic" +
      "t/prediction/tabular_regression.proto\032Og" +
      "oogle/cloud/aiplatform/v1beta1/schema/pr" +
      "edict/prediction/text_extraction.proto\032N" +
      "google/cloud/aiplatform/v1beta1/schema/p" +
      "redict/prediction/text_sentiment.proto\032W" +
      "google/cloud/aiplatform/v1beta1/schema/p" +
      "redict/prediction/time_series_forecastin" +
      "g.proto\032Xgoogle/cloud/aiplatform/v1beta1" +
      "/schema/predict/prediction/video_action_" +
      "recognition.proto\032Tgoogle/cloud/aiplatfo" +
      "rm/v1beta1/schema/predict/prediction/vid" +
      "eo_classification.proto\032Ugoogle/cloud/ai" +
      "platform/v1beta1/schema/predict/predicti" +
      "on/video_object_tracking.proto\032Vgoogle/c" +
      "loud/aiplatform/v1beta1/schema/trainingj" +
      "ob/definition/automl_forecasting.proto\032_" +
      "google/cloud/aiplatform/v1beta1/schema/t" +
      "rainingjob/definition/automl_image_class" +
      "ification.proto\032agoogle/cloud/aiplatform" +
      "/v1beta1/schema/trainingjob/definition/a" +
      "utoml_image_object_detection.proto\032]goog" +
      "le/cloud/aiplatform/v1beta1/schema/train" +
      "ingjob/definition/automl_image_segmentat" +
      "ion.proto\032Qgoogle/cloud/aiplatform/v1bet" +
      "a1/schema/trainingjob/definition/automl_" +
      "tables.proto\032^google/cloud/aiplatform/v1" +
      "beta1/schema/trainingjob/definition/auto" +
      "ml_text_classification.proto\032Zgoogle/clo" +
      "ud/aiplatform/v1beta1/schema/trainingjob" +
      "/definition/automl_text_extraction.proto" +
      "\032Ygoogle/cloud/aiplatform/v1beta1/schema" +
      "/trainingjob/definition/automl_text_sent" +
      "iment.proto\032cgoogle/cloud/aiplatform/v1b" +
      "eta1/schema/trainingjob/definition/autom" +
      "l_video_action_recognition.proto\032_google" +
      "/cloud/aiplatform/v1beta1/schema/trainin" +
      "gjob/definition/automl_video_classificat" +
      "ion.proto\032`google/cloud/aiplatform/v1bet" +
      "a1/schema/trainingjob/definition/automl_" +
      "video_object_tracking.proto\032fgoogle/clou" +
      "d/aiplatform/v1beta1/schema/trainingjob/" +
      "definition/export_evaluated_data_items_c" +
      "onfig.proto\"\355\034\n\025TrainingJobDefinition\022m\n" +
      "\023auto_ml_forecasting\030\001 \001(\0132P.google.clou" +
      "d.aiplatform.v1beta1.schema.trainingjob." +
      "definition.AutoMlForecasting\022z\n\032auto_ml_" +
      "forecasting_inputs\030\002 \001(\0132V.google.cloud." +
      "aiplatform.v1beta1.schema.trainingjob.de" +
      "finition.AutoMlForecastingInputs\022~\n\034auto" +
      "_ml_forecasting_metadata\030\003 \001(\0132X.google." +
      "cloud.aiplatform.v1beta1.schema.training" +
      "job.definition.AutoMlForecastingMetadata" +
      "\022~\n\034auto_ml_image_classification\030\004 \001(\0132X" +
      ".google.cloud.aiplatform.v1beta1.schema." +
      "trainingjob.definition.AutoMlImageClassi" +
      "fication\022\213\001\n#auto_ml_image_classificatio" +
      "n_inputs\030\005 \001(\0132^.google.cloud.aiplatform" +
      ".v1beta1.schema.trainingjob.definition.A" +
      "utoMlImageClassificationInputs\022\217\001\n%auto_" +
      "ml_image_classification_metadata\030\006 \001(\0132`" +
      ".google.cloud.aiplatform.v1beta1.schema." +
      "trainingjob.definition.AutoMlImageClassi" +
      "ficationMetadata\022\201\001\n\036auto_ml_image_objec" +
      "t_detection\030\007 \001(\0132Y.google.cloud.aiplatf" +
      "orm.v1beta1.schema.trainingjob.definitio" +
      "n.AutoMlImageObjectDetection\022\216\001\n%auto_ml" +
      "_image_object_detection_inputs\030\010 \001(\0132_.g" +
      "oogle.cloud.aiplatform.v1beta1.schema.tr" +
      "ainingjob.definition.AutoMlImageObjectDe" +
      "tectionInputs\022\222\001\n\'auto_ml_image_object_d" +
      "etection_metadata\030\t \001(\0132a.google.cloud.a" +
      "iplatform.v1beta1.schema.trainingjob.def" +
      "inition.AutoMlImageObjectDetectionMetada" +
      "ta\022z\n\032auto_ml_image_segmentation\030\n \001(\0132V" +
      ".google.cloud.aiplatform.v1beta1.schema." +
      "trainingjob.definition.AutoMlImageSegmen" +
      "tation\022\207\001\n!auto_ml_image_segmentation_in" +
      "puts\030\013 \001(\0132\\.google.cloud.aiplatform.v1b" +
      "eta1.schema.trainingjob.definition.AutoM" +
      "lImageSegmentationInputs\022\213\001\n#auto_ml_ima" +
      "ge_segmentation_metadata\030\014 \001(\0132^.google." +
      "cloud.aiplatform.v1beta1.schema.training" +
      "job.definition.AutoMlImageSegmentationMe" +
      "tadata\022c\n\016auto_ml_tables\030\r \001(\0132K.google." +
      "cloud.aiplatform.v1beta1.schema.training" +
      "job.definition.AutoMlTables\022p\n\025auto_ml_t" +
      "ables_inputs\030\016 \001(\0132Q.google.cloud.aiplat" +
      "form.v1beta1.schema.trainingjob.definiti" +
      "on.AutoMlTablesInputs\022t\n\027auto_ml_tables_" +
      "metadata\030\017 \001(\0132S.google.cloud.aiplatform" +
      ".v1beta1.schema.trainingjob.definition.A" +
      "utoMlTablesMetadata\022|\n\033auto_ml_text_clas" +
      "sification\030\020 \001(\0132W.google.cloud.aiplatfo" +
      "rm.v1beta1.schema.trainingjob.definition" +
      ".AutoMlTextClassification\022\211\001\n\"auto_ml_te" +
      "xt_classification_inputs\030\021 \001(\0132].google." +
      "cloud.aiplatform.v1beta1.schema.training" +
      "job.definition.AutoMlTextClassificationI" +
      "nputs\022t\n\027auto_ml_text_extraction\030\022 \001(\0132S" +
      ".google.cloud.aiplatform.v1beta1.schema." +
      "trainingjob.definition.AutoMlTextExtract" +
      "ion\022\201\001\n\036auto_ml_text_extraction_inputs\030\023" +
      " \001(\0132Y.google.cloud.aiplatform.v1beta1.s" +
      "chema.trainingjob.definition.AutoMlTextE" +
      "xtractionInputs\022r\n\026auto_ml_text_sentimen" +
      "t\030\024 \001(\0132R.google.cloud.aiplatform.v1beta" +
      "1.schema.trainingjob.definition.AutoMlTe" +
      "xtSentiment\022\177\n\035auto_ml_text_sentiment_in" +
      "puts\030\025 \001(\0132X.google.cloud.aiplatform.v1b" +
      "eta1.schema.trainingjob.definition.AutoM" +
      "lTextSentimentInputs\022\205\001\n auto_ml_video_a" +
      "ction_recognition\030\026 \001(\0132[.google.cloud.a" +
      "iplatform.v1beta1.schema.trainingjob.def" +
      "inition.AutoMlVideoActionRecognition\022\222\001\n" +
      "\'auto_ml_video_action_recognition_inputs" +
      "\030\027 \001(\0132a.google.cloud.aiplatform.v1beta1" +
      ".schema.trainingjob.definition.AutoMlVid" +
      "eoActionRecognitionInputs\022~\n\034auto_ml_vid" +
      "eo_classification\030\030 \001(\0132X.google.cloud.a" +
      "iplatform.v1beta1.schema.trainingjob.def" +
      "inition.AutoMlVideoClassification\022\213\001\n#au" +
      "to_ml_video_classification_inputs\030\031 \001(\0132" +
      "^.google.cloud.aiplatform.v1beta1.schema" +
      ".trainingjob.definition.AutoMlVideoClass" +
      "ificationInputs\022\177\n\035auto_ml_video_object_" +
      "tracking\030\032 \001(\0132X.google.cloud.aiplatform" +
      ".v1beta1.schema.trainingjob.definition.A" +
      "utoMlVideoObjectTracking\022\214\001\n$auto_ml_vid" +
      "eo_object_tracking_inputs\030\033 \001(\0132^.google" +
      ".cloud.aiplatform.v1beta1.schema.trainin" +
      "gjob.definition.AutoMlVideoObjectTrackin" +
      "gInputs\022\211\001\n\"export_evaluated_data_items_" +
      "config\030\034 \001(\0132].google.cloud.aiplatform.v" +
      "1beta1.schema.trainingjob.definition.Exp" +
      "ortEvaluatedDataItemsConfig\"\254\n\n\020PredictI" +
      "nstances\022\220\001\n(image_classification_predic" +
      "tion_instance\030\001 \001(\0132^.google.cloud.aipla" +
      "tform.v1beta1.schema.predict.instance.Im" +
      "ageClassificationPredictionInstance\022\223\001\n*" +
      "image_object_detection_prediction_instan" +
      "ce\030\002 \001(\0132_.google.cloud.aiplatform.v1bet" +
      "a1.schema.predict.instance.ImageObjectDe" +
      "tectionPredictionInstance\022\214\001\n&image_segm" +
      "entation_prediction_instance\030\003 \001(\0132\\.goo" +
      "gle.cloud.aiplatform.v1beta1.schema.pred" +
      "ict.instance.ImageSegmentationPrediction" +
      "Instance\022\216\001\n\'text_classification_predict" +
      "ion_instance\030\004 \001(\0132].google.cloud.aiplat" +
      "form.v1beta1.schema.predict.instance.Tex" +
      "tClassificationPredictionInstance\022\206\001\n#te" +
      "xt_extraction_prediction_instance\030\005 \001(\0132" +
      "Y.google.cloud.aiplatform.v1beta1.schema" +
      ".predict.instance.TextExtractionPredicti" +
      "onInstance\022\204\001\n\"text_sentiment_prediction" +
      "_instance\030\006 \001(\0132X.google.cloud.aiplatfor" +
      "m.v1beta1.schema.predict.instance.TextSe" +
      "ntimentPredictionInstance\022\227\001\n,video_acti" +
      "on_recognition_prediction_instance\030\007 \001(\013" +
      "2a.google.cloud.aiplatform.v1beta1.schem" +
      "a.predict.instance.VideoActionRecognitio" +
      "nPredictionInstance\022\220\001\n(video_classifica" +
      "tion_prediction_instance\030\010 \001(\0132^.google." +
      "cloud.aiplatform.v1beta1.schema.predict." +
      "instance.VideoClassificationPredictionIn" +
      "stance\022\221\001\n)video_object_tracking_predict" +
      "ion_instance\030\t \001(\0132^.google.cloud.aiplat" +
      "form.v1beta1.schema.predict.instance.Vid" +
      "eoObjectTrackingPredictionInstance\"\344\006\n\rP" +
      "redictParams\022\212\001\n&image_classification_pr" +
      "ediction_params\030\001 \001(\0132Z.google.cloud.aip" +
      "latform.v1beta1.schema.predict.params.Im" +
      "ageClassificationPredictionParams\022\215\001\n(im" +
      "age_object_detection_prediction_params\030\002" +
      " \001(\0132[.google.cloud.aiplatform.v1beta1.s" +
      "chema.predict.params.ImageObjectDetectio" +
      "nPredictionParams\022\206\001\n$image_segmentation" +
      "_prediction_params\030> \001(\0132X.google.cloud." +
      "aiplatform.v1beta1.schema.predict.params" +
      ".ImageSegmentationPredictionParams\022\221\001\n*v" +
      "ideo_action_recognition_prediction_param" +
      "s\030\003 \001(\0132].google.cloud.aiplatform.v1beta" +
      "1.schema.predict.params.VideoActionRecog" +
      "nitionPredictionParams\022\212\001\n&video_classif" +
      "ication_prediction_params\030\004 \001(\0132Z.google" +
      ".cloud.aiplatform.v1beta1.schema.predict" +
      ".params.VideoClassificationPredictionPar" +
      "ams\022\213\001\n\'video_object_tracking_prediction" +
      "_params\030\005 \001(\0132Z.google.cloud.aiplatform." +
      "v1beta1.schema.predict.params.VideoObjec" +
      "tTrackingPredictionParams\"\215\014\n\021Prediction" +
      "Results\022\203\001\n classification_prediction_re" +
      "sult\030\001 \001(\0132Y.google.cloud.aiplatform.v1b" +
      "eta1.schema.predict.prediction.Classific" +
      "ationPredictionResult\022\206\001\n\035image_object_d" +
      "etection_result\030\002 \001(\0132_.google.cloud.aip" +
      "latform.v1beta1.schema.predict.predictio" +
      "n.ImageObjectDetectionPredictionResult\022\212" +
      "\001\n$image_segmentation_prediction_result\030" +
      "\003 \001(\0132\\.google.cloud.aiplatform.v1beta1." +
      "schema.predict.prediction.ImageSegmentat" +
      "ionPredictionResult\022\222\001\n(tabular_classifi" +
      "cation_prediction_result\030\004 \001(\0132`.google." +
      "cloud.aiplatform.v1beta1.schema.predict." +
      "prediction.TabularClassificationPredicti" +
      "onResult\022\212\001\n$tabular_regression_predicti" +
      "on_result\030\005 \001(\0132\\.google.cloud.aiplatfor" +
      "m.v1beta1.schema.predict.prediction.Tabu" +
      "larRegressionPredictionResult\022\204\001\n!text_e" +
      "xtraction_prediction_result\030\006 \001(\0132Y.goog" +
      "le.cloud.aiplatform.v1beta1.schema.predi" +
      "ct.prediction.TextExtractionPredictionRe" +
      "sult\022\202\001\n text_sentiment_prediction_resul" +
      "t\030\007 \001(\0132X.google.cloud.aiplatform.v1beta" +
      "1.schema.predict.prediction.TextSentimen" +
      "tPredictionResult\022\223\001\n)time_series_foreca" +
      "sting_prediction_result\030\010 \001(\0132`.google.c" +
      "loud.aiplatform.v1beta1.schema.predict.p" +
      "rediction.TimeSeriesForecastingPredictio" +
      "nResult\022\212\001\n\037video_action_recognition_res" +
      "ult\030\t \001(\0132a.google.cloud.aiplatform.v1be" +
      "ta1.schema.predict.prediction.VideoActio" +
      "nRecognitionPredictionResult\022\203\001\n\033video_c" +
      "lassification_result\030\n \001(\0132^.google.clou" +
      "d.aiplatform.v1beta1.schema.predict.pred" +
      "iction.VideoClassificationPredictionResu" +
      "lt\022\204\001\n\034video_object_tracking_result\030\013 \001(" +
      "\0132^.google.cloud.aiplatform.v1beta1.sche" +
      "ma.predict.prediction.VideoClassificatio" +
      "nPredictionResultB;\n#com.google.cloud.ai" +
      "platform.v1beta1B\022EnhancedTypesProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstanceProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoObjectTrackingPredictionResultProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLForecastingProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageClassificationProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageObjectDetectionProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageSegmentationProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTablesProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextClassificationProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextExtractionProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextSentimentProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoActionRecognitionProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoClassificationProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoObjectTrackingProto.getDescriptor(),
          com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.ExportEvaluatedDataItemsConfigProto.getDescriptor(),
        });
    internal_static_google_cloud_aiplatform_v1beta1_TrainingJobDefinition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1beta1_TrainingJobDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_aiplatform_v1beta1_TrainingJobDefinition_descriptor,
        new java.lang.String[] { "AutoMlForecasting", "AutoMlForecastingInputs", "AutoMlForecastingMetadata", "AutoMlImageClassification", "AutoMlImageClassificationInputs", "AutoMlImageClassificationMetadata", "AutoMlImageObjectDetection", "AutoMlImageObjectDetectionInputs", "AutoMlImageObjectDetectionMetadata", "AutoMlImageSegmentation", "AutoMlImageSegmentationInputs", "AutoMlImageSegmentationMetadata", "AutoMlTables", "AutoMlTablesInputs", "AutoMlTablesMetadata", "AutoMlTextClassification", "AutoMlTextClassificationInputs", "AutoMlTextExtraction", "AutoMlTextExtractionInputs", "AutoMlTextSentiment", "AutoMlTextSentimentInputs", "AutoMlVideoActionRecognition", "AutoMlVideoActionRecognitionInputs", "AutoMlVideoClassification", "AutoMlVideoClassificationInputs", "AutoMlVideoObjectTracking", "AutoMlVideoObjectTrackingInputs", "ExportEvaluatedDataItemsConfig", });
    internal_static_google_cloud_aiplatform_v1beta1_PredictInstances_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1beta1_PredictInstances_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_aiplatform_v1beta1_PredictInstances_descriptor,
        new java.lang.String[] { "ImageClassificationPredictionInstance", "ImageObjectDetectionPredictionInstance", "ImageSegmentationPredictionInstance", "TextClassificationPredictionInstance", "TextExtractionPredictionInstance", "TextSentimentPredictionInstance", "VideoActionRecognitionPredictionInstance", "VideoClassificationPredictionInstance", "VideoObjectTrackingPredictionInstance", });
    internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1beta1_PredictParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor,
        new java.lang.String[] { "ImageClassificationPredictionParams", "ImageObjectDetectionPredictionParams", "ImageSegmentationPredictionParams", "VideoActionRecognitionPredictionParams", "VideoClassificationPredictionParams", "VideoObjectTrackingPredictionParams", });
    internal_static_google_cloud_aiplatform_v1beta1_PredictionResults_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1beta1_PredictionResults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_aiplatform_v1beta1_PredictionResults_descriptor,
        new java.lang.String[] { "ClassificationPredictionResult", "ImageObjectDetectionResult", "ImageSegmentationPredictionResult", "TabularClassificationPredictionResult", "TabularRegressionPredictionResult", "TextExtractionPredictionResult", "TextSentimentPredictionResult", "TimeSeriesForecastingPredictionResult", "VideoActionRecognitionResult", "VideoClassificationResult", "VideoObjectTrackingResult", });
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstanceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoObjectTrackingPredictionResultProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLForecastingProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageClassificationProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageObjectDetectionProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLImageSegmentationProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTablesProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextClassificationProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextExtractionProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLTextSentimentProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoActionRecognitionProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoClassificationProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMLVideoObjectTrackingProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.ExportEvaluatedDataItemsConfigProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
