// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/enhanced_types.proto

package com.google.cloud.aiplatform.v1beta1;

public interface PredictInstancesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.aiplatform.v1beta1.PredictInstances)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstance image_classification_prediction_instance = 1;</code>
   * @return Whether the imageClassificationPredictionInstance field is set.
   */
  boolean hasImageClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstance image_classification_prediction_instance = 1;</code>
   * @return The imageClassificationPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstance getImageClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstance image_classification_prediction_instance = 1;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageClassificationPredictionInstanceOrBuilder getImageClassificationPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstance image_object_detection_prediction_instance = 2;</code>
   * @return Whether the imageObjectDetectionPredictionInstance field is set.
   */
  boolean hasImageObjectDetectionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstance image_object_detection_prediction_instance = 2;</code>
   * @return The imageObjectDetectionPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstance getImageObjectDetectionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstance image_object_detection_prediction_instance = 2;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageObjectDetectionPredictionInstanceOrBuilder getImageObjectDetectionPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstance image_segmentation_prediction_instance = 3;</code>
   * @return Whether the imageSegmentationPredictionInstance field is set.
   */
  boolean hasImageSegmentationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstance image_segmentation_prediction_instance = 3;</code>
   * @return The imageSegmentationPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstance getImageSegmentationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstance image_segmentation_prediction_instance = 3;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.ImageSegmentationPredictionInstanceOrBuilder getImageSegmentationPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstance text_classification_prediction_instance = 4;</code>
   * @return Whether the textClassificationPredictionInstance field is set.
   */
  boolean hasTextClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstance text_classification_prediction_instance = 4;</code>
   * @return The textClassificationPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstance getTextClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstance text_classification_prediction_instance = 4;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextClassificationPredictionInstanceOrBuilder getTextClassificationPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstance text_extraction_prediction_instance = 5;</code>
   * @return Whether the textExtractionPredictionInstance field is set.
   */
  boolean hasTextExtractionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstance text_extraction_prediction_instance = 5;</code>
   * @return The textExtractionPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstance getTextExtractionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstance text_extraction_prediction_instance = 5;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextExtractionPredictionInstanceOrBuilder getTextExtractionPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstance text_sentiment_prediction_instance = 6;</code>
   * @return Whether the textSentimentPredictionInstance field is set.
   */
  boolean hasTextSentimentPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstance text_sentiment_prediction_instance = 6;</code>
   * @return The textSentimentPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstance getTextSentimentPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstance text_sentiment_prediction_instance = 6;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.TextSentimentPredictionInstanceOrBuilder getTextSentimentPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstance video_action_recognition_prediction_instance = 7;</code>
   * @return Whether the videoActionRecognitionPredictionInstance field is set.
   */
  boolean hasVideoActionRecognitionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstance video_action_recognition_prediction_instance = 7;</code>
   * @return The videoActionRecognitionPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstance getVideoActionRecognitionPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstance video_action_recognition_prediction_instance = 7;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoActionRecognitionPredictionInstanceOrBuilder getVideoActionRecognitionPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstance video_classification_prediction_instance = 8;</code>
   * @return Whether the videoClassificationPredictionInstance field is set.
   */
  boolean hasVideoClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstance video_classification_prediction_instance = 8;</code>
   * @return The videoClassificationPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstance getVideoClassificationPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstance video_classification_prediction_instance = 8;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoClassificationPredictionInstanceOrBuilder getVideoClassificationPredictionInstanceOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstance video_object_tracking_prediction_instance = 9;</code>
   * @return Whether the videoObjectTrackingPredictionInstance field is set.
   */
  boolean hasVideoObjectTrackingPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstance video_object_tracking_prediction_instance = 9;</code>
   * @return The videoObjectTrackingPredictionInstance.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstance getVideoObjectTrackingPredictionInstance();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstance video_object_tracking_prediction_instance = 9;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.instance.VideoObjectTrackingPredictionInstanceOrBuilder getVideoObjectTrackingPredictionInstanceOrBuilder();
}
