// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/enhanced_types.proto

package com.google.cloud.aiplatform.v1beta1;

public interface PredictParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.aiplatform.v1beta1.PredictParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   * @return Whether the imageClassificationPredictionParams field is set.
   */
  boolean hasImageClassificationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   * @return The imageClassificationPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams getImageClassificationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder getImageClassificationPredictionParamsOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   * @return Whether the imageObjectDetectionPredictionParams field is set.
   */
  boolean hasImageObjectDetectionPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   * @return The imageObjectDetectionPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams getImageObjectDetectionPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder getImageObjectDetectionPredictionParamsOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   * @return Whether the imageSegmentationPredictionParams field is set.
   */
  boolean hasImageSegmentationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   * @return The imageSegmentationPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams getImageSegmentationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder getImageSegmentationPredictionParamsOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   * @return Whether the videoActionRecognitionPredictionParams field is set.
   */
  boolean hasVideoActionRecognitionPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   * @return The videoActionRecognitionPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams getVideoActionRecognitionPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder getVideoActionRecognitionPredictionParamsOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   * @return Whether the videoClassificationPredictionParams field is set.
   */
  boolean hasVideoClassificationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   * @return The videoClassificationPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams getVideoClassificationPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder getVideoClassificationPredictionParamsOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   * @return Whether the videoObjectTrackingPredictionParams field is set.
   */
  boolean hasVideoObjectTrackingPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   * @return The videoObjectTrackingPredictionParams.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams getVideoObjectTrackingPredictionParams();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder getVideoObjectTrackingPredictionParamsOrBuilder();
}
