// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/enhanced_types.proto

package com.google.cloud.aiplatform.v1beta1;

/**
 * <pre>
 * FOR LIBRARY GENERATION PURPOSES ONLY. DO NOT USE.
 * TODO(erschmid): Mark all fields as output-only to restrict usage by customers?
 * </pre>
 *
 * Protobuf type {@code google.cloud.aiplatform.v1beta1.PredictParams}
 */
public final class PredictParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.cloud.aiplatform.v1beta1.PredictParams)
    PredictParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PredictParams.newBuilder() to construct.
  private PredictParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PredictParams() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PredictParams();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PredictParams(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder subBuilder = null;
            if (imageClassificationPredictionParams_ != null) {
              subBuilder = imageClassificationPredictionParams_.toBuilder();
            }
            imageClassificationPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imageClassificationPredictionParams_);
              imageClassificationPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder subBuilder = null;
            if (imageObjectDetectionPredictionParams_ != null) {
              subBuilder = imageObjectDetectionPredictionParams_.toBuilder();
            }
            imageObjectDetectionPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imageObjectDetectionPredictionParams_);
              imageObjectDetectionPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder subBuilder = null;
            if (videoActionRecognitionPredictionParams_ != null) {
              subBuilder = videoActionRecognitionPredictionParams_.toBuilder();
            }
            videoActionRecognitionPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(videoActionRecognitionPredictionParams_);
              videoActionRecognitionPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder subBuilder = null;
            if (videoClassificationPredictionParams_ != null) {
              subBuilder = videoClassificationPredictionParams_.toBuilder();
            }
            videoClassificationPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(videoClassificationPredictionParams_);
              videoClassificationPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder subBuilder = null;
            if (videoObjectTrackingPredictionParams_ != null) {
              subBuilder = videoObjectTrackingPredictionParams_.toBuilder();
            }
            videoObjectTrackingPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(videoObjectTrackingPredictionParams_);
              videoObjectTrackingPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 498: {
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder subBuilder = null;
            if (imageSegmentationPredictionParams_ != null) {
              subBuilder = imageSegmentationPredictionParams_.toBuilder();
            }
            imageSegmentationPredictionParams_ = input.readMessage(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imageSegmentationPredictionParams_);
              imageSegmentationPredictionParams_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.aiplatform.v1beta1.EnhancedTypesProto.internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.aiplatform.v1beta1.EnhancedTypesProto.internal_static_google_cloud_aiplatform_v1beta1_PredictParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.aiplatform.v1beta1.PredictParams.class, com.google.cloud.aiplatform.v1beta1.PredictParams.Builder.class);
  }

  public static final int IMAGE_CLASSIFICATION_PREDICTION_PARAMS_FIELD_NUMBER = 1;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams imageClassificationPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   * @return Whether the imageClassificationPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasImageClassificationPredictionParams() {
    return imageClassificationPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   * @return The imageClassificationPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams getImageClassificationPredictionParams() {
    return imageClassificationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.getDefaultInstance() : imageClassificationPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder getImageClassificationPredictionParamsOrBuilder() {
    return getImageClassificationPredictionParams();
  }

  public static final int IMAGE_OBJECT_DETECTION_PREDICTION_PARAMS_FIELD_NUMBER = 2;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams imageObjectDetectionPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   * @return Whether the imageObjectDetectionPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasImageObjectDetectionPredictionParams() {
    return imageObjectDetectionPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   * @return The imageObjectDetectionPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams getImageObjectDetectionPredictionParams() {
    return imageObjectDetectionPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.getDefaultInstance() : imageObjectDetectionPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder getImageObjectDetectionPredictionParamsOrBuilder() {
    return getImageObjectDetectionPredictionParams();
  }

  public static final int IMAGE_SEGMENTATION_PREDICTION_PARAMS_FIELD_NUMBER = 62;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams imageSegmentationPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   * @return Whether the imageSegmentationPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasImageSegmentationPredictionParams() {
    return imageSegmentationPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   * @return The imageSegmentationPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams getImageSegmentationPredictionParams() {
    return imageSegmentationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.getDefaultInstance() : imageSegmentationPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder getImageSegmentationPredictionParamsOrBuilder() {
    return getImageSegmentationPredictionParams();
  }

  public static final int VIDEO_ACTION_RECOGNITION_PREDICTION_PARAMS_FIELD_NUMBER = 3;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams videoActionRecognitionPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   * @return Whether the videoActionRecognitionPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasVideoActionRecognitionPredictionParams() {
    return videoActionRecognitionPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   * @return The videoActionRecognitionPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams getVideoActionRecognitionPredictionParams() {
    return videoActionRecognitionPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.getDefaultInstance() : videoActionRecognitionPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder getVideoActionRecognitionPredictionParamsOrBuilder() {
    return getVideoActionRecognitionPredictionParams();
  }

  public static final int VIDEO_CLASSIFICATION_PREDICTION_PARAMS_FIELD_NUMBER = 4;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams videoClassificationPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   * @return Whether the videoClassificationPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasVideoClassificationPredictionParams() {
    return videoClassificationPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   * @return The videoClassificationPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams getVideoClassificationPredictionParams() {
    return videoClassificationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.getDefaultInstance() : videoClassificationPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder getVideoClassificationPredictionParamsOrBuilder() {
    return getVideoClassificationPredictionParams();
  }

  public static final int VIDEO_OBJECT_TRACKING_PREDICTION_PARAMS_FIELD_NUMBER = 5;
  private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams videoObjectTrackingPredictionParams_;
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   * @return Whether the videoObjectTrackingPredictionParams field is set.
   */
  @java.lang.Override
  public boolean hasVideoObjectTrackingPredictionParams() {
    return videoObjectTrackingPredictionParams_ != null;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   * @return The videoObjectTrackingPredictionParams.
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams getVideoObjectTrackingPredictionParams() {
    return videoObjectTrackingPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.getDefaultInstance() : videoObjectTrackingPredictionParams_;
  }
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
   */
  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder getVideoObjectTrackingPredictionParamsOrBuilder() {
    return getVideoObjectTrackingPredictionParams();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (imageClassificationPredictionParams_ != null) {
      output.writeMessage(1, getImageClassificationPredictionParams());
    }
    if (imageObjectDetectionPredictionParams_ != null) {
      output.writeMessage(2, getImageObjectDetectionPredictionParams());
    }
    if (videoActionRecognitionPredictionParams_ != null) {
      output.writeMessage(3, getVideoActionRecognitionPredictionParams());
    }
    if (videoClassificationPredictionParams_ != null) {
      output.writeMessage(4, getVideoClassificationPredictionParams());
    }
    if (videoObjectTrackingPredictionParams_ != null) {
      output.writeMessage(5, getVideoObjectTrackingPredictionParams());
    }
    if (imageSegmentationPredictionParams_ != null) {
      output.writeMessage(62, getImageSegmentationPredictionParams());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (imageClassificationPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImageClassificationPredictionParams());
    }
    if (imageObjectDetectionPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getImageObjectDetectionPredictionParams());
    }
    if (videoActionRecognitionPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVideoActionRecognitionPredictionParams());
    }
    if (videoClassificationPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getVideoClassificationPredictionParams());
    }
    if (videoObjectTrackingPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVideoObjectTrackingPredictionParams());
    }
    if (imageSegmentationPredictionParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(62, getImageSegmentationPredictionParams());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.aiplatform.v1beta1.PredictParams)) {
      return super.equals(obj);
    }
    com.google.cloud.aiplatform.v1beta1.PredictParams other = (com.google.cloud.aiplatform.v1beta1.PredictParams) obj;

    if (hasImageClassificationPredictionParams() != other.hasImageClassificationPredictionParams()) return false;
    if (hasImageClassificationPredictionParams()) {
      if (!getImageClassificationPredictionParams()
          .equals(other.getImageClassificationPredictionParams())) return false;
    }
    if (hasImageObjectDetectionPredictionParams() != other.hasImageObjectDetectionPredictionParams()) return false;
    if (hasImageObjectDetectionPredictionParams()) {
      if (!getImageObjectDetectionPredictionParams()
          .equals(other.getImageObjectDetectionPredictionParams())) return false;
    }
    if (hasImageSegmentationPredictionParams() != other.hasImageSegmentationPredictionParams()) return false;
    if (hasImageSegmentationPredictionParams()) {
      if (!getImageSegmentationPredictionParams()
          .equals(other.getImageSegmentationPredictionParams())) return false;
    }
    if (hasVideoActionRecognitionPredictionParams() != other.hasVideoActionRecognitionPredictionParams()) return false;
    if (hasVideoActionRecognitionPredictionParams()) {
      if (!getVideoActionRecognitionPredictionParams()
          .equals(other.getVideoActionRecognitionPredictionParams())) return false;
    }
    if (hasVideoClassificationPredictionParams() != other.hasVideoClassificationPredictionParams()) return false;
    if (hasVideoClassificationPredictionParams()) {
      if (!getVideoClassificationPredictionParams()
          .equals(other.getVideoClassificationPredictionParams())) return false;
    }
    if (hasVideoObjectTrackingPredictionParams() != other.hasVideoObjectTrackingPredictionParams()) return false;
    if (hasVideoObjectTrackingPredictionParams()) {
      if (!getVideoObjectTrackingPredictionParams()
          .equals(other.getVideoObjectTrackingPredictionParams())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImageClassificationPredictionParams()) {
      hash = (37 * hash) + IMAGE_CLASSIFICATION_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getImageClassificationPredictionParams().hashCode();
    }
    if (hasImageObjectDetectionPredictionParams()) {
      hash = (37 * hash) + IMAGE_OBJECT_DETECTION_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getImageObjectDetectionPredictionParams().hashCode();
    }
    if (hasImageSegmentationPredictionParams()) {
      hash = (37 * hash) + IMAGE_SEGMENTATION_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getImageSegmentationPredictionParams().hashCode();
    }
    if (hasVideoActionRecognitionPredictionParams()) {
      hash = (37 * hash) + VIDEO_ACTION_RECOGNITION_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getVideoActionRecognitionPredictionParams().hashCode();
    }
    if (hasVideoClassificationPredictionParams()) {
      hash = (37 * hash) + VIDEO_CLASSIFICATION_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getVideoClassificationPredictionParams().hashCode();
    }
    if (hasVideoObjectTrackingPredictionParams()) {
      hash = (37 * hash) + VIDEO_OBJECT_TRACKING_PREDICTION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getVideoObjectTrackingPredictionParams().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.aiplatform.v1beta1.PredictParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.aiplatform.v1beta1.PredictParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FOR LIBRARY GENERATION PURPOSES ONLY. DO NOT USE.
   * TODO(erschmid): Mark all fields as output-only to restrict usage by customers?
   * </pre>
   *
   * Protobuf type {@code google.cloud.aiplatform.v1beta1.PredictParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.aiplatform.v1beta1.PredictParams)
      com.google.cloud.aiplatform.v1beta1.PredictParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.aiplatform.v1beta1.EnhancedTypesProto.internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.aiplatform.v1beta1.EnhancedTypesProto.internal_static_google_cloud_aiplatform_v1beta1_PredictParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.aiplatform.v1beta1.PredictParams.class, com.google.cloud.aiplatform.v1beta1.PredictParams.Builder.class);
    }

    // Construct using com.google.cloud.aiplatform.v1beta1.PredictParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (imageClassificationPredictionParamsBuilder_ == null) {
        imageClassificationPredictionParams_ = null;
      } else {
        imageClassificationPredictionParams_ = null;
        imageClassificationPredictionParamsBuilder_ = null;
      }
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        imageObjectDetectionPredictionParams_ = null;
      } else {
        imageObjectDetectionPredictionParams_ = null;
        imageObjectDetectionPredictionParamsBuilder_ = null;
      }
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        imageSegmentationPredictionParams_ = null;
      } else {
        imageSegmentationPredictionParams_ = null;
        imageSegmentationPredictionParamsBuilder_ = null;
      }
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        videoActionRecognitionPredictionParams_ = null;
      } else {
        videoActionRecognitionPredictionParams_ = null;
        videoActionRecognitionPredictionParamsBuilder_ = null;
      }
      if (videoClassificationPredictionParamsBuilder_ == null) {
        videoClassificationPredictionParams_ = null;
      } else {
        videoClassificationPredictionParams_ = null;
        videoClassificationPredictionParamsBuilder_ = null;
      }
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        videoObjectTrackingPredictionParams_ = null;
      } else {
        videoObjectTrackingPredictionParams_ = null;
        videoObjectTrackingPredictionParamsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.aiplatform.v1beta1.EnhancedTypesProto.internal_static_google_cloud_aiplatform_v1beta1_PredictParams_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.aiplatform.v1beta1.PredictParams getDefaultInstanceForType() {
      return com.google.cloud.aiplatform.v1beta1.PredictParams.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.aiplatform.v1beta1.PredictParams build() {
      com.google.cloud.aiplatform.v1beta1.PredictParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.aiplatform.v1beta1.PredictParams buildPartial() {
      com.google.cloud.aiplatform.v1beta1.PredictParams result = new com.google.cloud.aiplatform.v1beta1.PredictParams(this);
      if (imageClassificationPredictionParamsBuilder_ == null) {
        result.imageClassificationPredictionParams_ = imageClassificationPredictionParams_;
      } else {
        result.imageClassificationPredictionParams_ = imageClassificationPredictionParamsBuilder_.build();
      }
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        result.imageObjectDetectionPredictionParams_ = imageObjectDetectionPredictionParams_;
      } else {
        result.imageObjectDetectionPredictionParams_ = imageObjectDetectionPredictionParamsBuilder_.build();
      }
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        result.imageSegmentationPredictionParams_ = imageSegmentationPredictionParams_;
      } else {
        result.imageSegmentationPredictionParams_ = imageSegmentationPredictionParamsBuilder_.build();
      }
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        result.videoActionRecognitionPredictionParams_ = videoActionRecognitionPredictionParams_;
      } else {
        result.videoActionRecognitionPredictionParams_ = videoActionRecognitionPredictionParamsBuilder_.build();
      }
      if (videoClassificationPredictionParamsBuilder_ == null) {
        result.videoClassificationPredictionParams_ = videoClassificationPredictionParams_;
      } else {
        result.videoClassificationPredictionParams_ = videoClassificationPredictionParamsBuilder_.build();
      }
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        result.videoObjectTrackingPredictionParams_ = videoObjectTrackingPredictionParams_;
      } else {
        result.videoObjectTrackingPredictionParams_ = videoObjectTrackingPredictionParamsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.aiplatform.v1beta1.PredictParams) {
        return mergeFrom((com.google.cloud.aiplatform.v1beta1.PredictParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.aiplatform.v1beta1.PredictParams other) {
      if (other == com.google.cloud.aiplatform.v1beta1.PredictParams.getDefaultInstance()) return this;
      if (other.hasImageClassificationPredictionParams()) {
        mergeImageClassificationPredictionParams(other.getImageClassificationPredictionParams());
      }
      if (other.hasImageObjectDetectionPredictionParams()) {
        mergeImageObjectDetectionPredictionParams(other.getImageObjectDetectionPredictionParams());
      }
      if (other.hasImageSegmentationPredictionParams()) {
        mergeImageSegmentationPredictionParams(other.getImageSegmentationPredictionParams());
      }
      if (other.hasVideoActionRecognitionPredictionParams()) {
        mergeVideoActionRecognitionPredictionParams(other.getVideoActionRecognitionPredictionParams());
      }
      if (other.hasVideoClassificationPredictionParams()) {
        mergeVideoClassificationPredictionParams(other.getVideoClassificationPredictionParams());
      }
      if (other.hasVideoObjectTrackingPredictionParams()) {
        mergeVideoObjectTrackingPredictionParams(other.getVideoObjectTrackingPredictionParams());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.aiplatform.v1beta1.PredictParams parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.aiplatform.v1beta1.PredictParams) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams imageClassificationPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder> imageClassificationPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     * @return Whether the imageClassificationPredictionParams field is set.
     */
    public boolean hasImageClassificationPredictionParams() {
      return imageClassificationPredictionParamsBuilder_ != null || imageClassificationPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     * @return The imageClassificationPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams getImageClassificationPredictionParams() {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        return imageClassificationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.getDefaultInstance() : imageClassificationPredictionParams_;
      } else {
        return imageClassificationPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public Builder setImageClassificationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams value) {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageClassificationPredictionParams_ = value;
        onChanged();
      } else {
        imageClassificationPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public Builder setImageClassificationPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder builderForValue) {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        imageClassificationPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        imageClassificationPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public Builder mergeImageClassificationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams value) {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        if (imageClassificationPredictionParams_ != null) {
          imageClassificationPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.newBuilder(imageClassificationPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          imageClassificationPredictionParams_ = value;
        }
        onChanged();
      } else {
        imageClassificationPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public Builder clearImageClassificationPredictionParams() {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        imageClassificationPredictionParams_ = null;
        onChanged();
      } else {
        imageClassificationPredictionParams_ = null;
        imageClassificationPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder getImageClassificationPredictionParamsBuilder() {
      
      onChanged();
      return getImageClassificationPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder getImageClassificationPredictionParamsOrBuilder() {
      if (imageClassificationPredictionParamsBuilder_ != null) {
        return imageClassificationPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return imageClassificationPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.getDefaultInstance() : imageClassificationPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams image_classification_prediction_params = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder> 
        getImageClassificationPredictionParamsFieldBuilder() {
      if (imageClassificationPredictionParamsBuilder_ == null) {
        imageClassificationPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageClassificationPredictionParamsOrBuilder>(
                getImageClassificationPredictionParams(),
                getParentForChildren(),
                isClean());
        imageClassificationPredictionParams_ = null;
      }
      return imageClassificationPredictionParamsBuilder_;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams imageObjectDetectionPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder> imageObjectDetectionPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     * @return Whether the imageObjectDetectionPredictionParams field is set.
     */
    public boolean hasImageObjectDetectionPredictionParams() {
      return imageObjectDetectionPredictionParamsBuilder_ != null || imageObjectDetectionPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     * @return The imageObjectDetectionPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams getImageObjectDetectionPredictionParams() {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        return imageObjectDetectionPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.getDefaultInstance() : imageObjectDetectionPredictionParams_;
      } else {
        return imageObjectDetectionPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public Builder setImageObjectDetectionPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams value) {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageObjectDetectionPredictionParams_ = value;
        onChanged();
      } else {
        imageObjectDetectionPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public Builder setImageObjectDetectionPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder builderForValue) {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        imageObjectDetectionPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        imageObjectDetectionPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public Builder mergeImageObjectDetectionPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams value) {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        if (imageObjectDetectionPredictionParams_ != null) {
          imageObjectDetectionPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.newBuilder(imageObjectDetectionPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          imageObjectDetectionPredictionParams_ = value;
        }
        onChanged();
      } else {
        imageObjectDetectionPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public Builder clearImageObjectDetectionPredictionParams() {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        imageObjectDetectionPredictionParams_ = null;
        onChanged();
      } else {
        imageObjectDetectionPredictionParams_ = null;
        imageObjectDetectionPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder getImageObjectDetectionPredictionParamsBuilder() {
      
      onChanged();
      return getImageObjectDetectionPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder getImageObjectDetectionPredictionParamsOrBuilder() {
      if (imageObjectDetectionPredictionParamsBuilder_ != null) {
        return imageObjectDetectionPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return imageObjectDetectionPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.getDefaultInstance() : imageObjectDetectionPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams image_object_detection_prediction_params = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder> 
        getImageObjectDetectionPredictionParamsFieldBuilder() {
      if (imageObjectDetectionPredictionParamsBuilder_ == null) {
        imageObjectDetectionPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageObjectDetectionPredictionParamsOrBuilder>(
                getImageObjectDetectionPredictionParams(),
                getParentForChildren(),
                isClean());
        imageObjectDetectionPredictionParams_ = null;
      }
      return imageObjectDetectionPredictionParamsBuilder_;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams imageSegmentationPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder> imageSegmentationPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     * @return Whether the imageSegmentationPredictionParams field is set.
     */
    public boolean hasImageSegmentationPredictionParams() {
      return imageSegmentationPredictionParamsBuilder_ != null || imageSegmentationPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     * @return The imageSegmentationPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams getImageSegmentationPredictionParams() {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        return imageSegmentationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.getDefaultInstance() : imageSegmentationPredictionParams_;
      } else {
        return imageSegmentationPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public Builder setImageSegmentationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams value) {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageSegmentationPredictionParams_ = value;
        onChanged();
      } else {
        imageSegmentationPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public Builder setImageSegmentationPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder builderForValue) {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        imageSegmentationPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        imageSegmentationPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public Builder mergeImageSegmentationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams value) {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        if (imageSegmentationPredictionParams_ != null) {
          imageSegmentationPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.newBuilder(imageSegmentationPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          imageSegmentationPredictionParams_ = value;
        }
        onChanged();
      } else {
        imageSegmentationPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public Builder clearImageSegmentationPredictionParams() {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        imageSegmentationPredictionParams_ = null;
        onChanged();
      } else {
        imageSegmentationPredictionParams_ = null;
        imageSegmentationPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder getImageSegmentationPredictionParamsBuilder() {
      
      onChanged();
      return getImageSegmentationPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder getImageSegmentationPredictionParamsOrBuilder() {
      if (imageSegmentationPredictionParamsBuilder_ != null) {
        return imageSegmentationPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return imageSegmentationPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.getDefaultInstance() : imageSegmentationPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams image_segmentation_prediction_params = 62;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder> 
        getImageSegmentationPredictionParamsFieldBuilder() {
      if (imageSegmentationPredictionParamsBuilder_ == null) {
        imageSegmentationPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.ImageSegmentationPredictionParamsOrBuilder>(
                getImageSegmentationPredictionParams(),
                getParentForChildren(),
                isClean());
        imageSegmentationPredictionParams_ = null;
      }
      return imageSegmentationPredictionParamsBuilder_;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams videoActionRecognitionPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder> videoActionRecognitionPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     * @return Whether the videoActionRecognitionPredictionParams field is set.
     */
    public boolean hasVideoActionRecognitionPredictionParams() {
      return videoActionRecognitionPredictionParamsBuilder_ != null || videoActionRecognitionPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     * @return The videoActionRecognitionPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams getVideoActionRecognitionPredictionParams() {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        return videoActionRecognitionPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.getDefaultInstance() : videoActionRecognitionPredictionParams_;
      } else {
        return videoActionRecognitionPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public Builder setVideoActionRecognitionPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams value) {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoActionRecognitionPredictionParams_ = value;
        onChanged();
      } else {
        videoActionRecognitionPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public Builder setVideoActionRecognitionPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder builderForValue) {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        videoActionRecognitionPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        videoActionRecognitionPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public Builder mergeVideoActionRecognitionPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams value) {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        if (videoActionRecognitionPredictionParams_ != null) {
          videoActionRecognitionPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.newBuilder(videoActionRecognitionPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          videoActionRecognitionPredictionParams_ = value;
        }
        onChanged();
      } else {
        videoActionRecognitionPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public Builder clearVideoActionRecognitionPredictionParams() {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        videoActionRecognitionPredictionParams_ = null;
        onChanged();
      } else {
        videoActionRecognitionPredictionParams_ = null;
        videoActionRecognitionPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder getVideoActionRecognitionPredictionParamsBuilder() {
      
      onChanged();
      return getVideoActionRecognitionPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder getVideoActionRecognitionPredictionParamsOrBuilder() {
      if (videoActionRecognitionPredictionParamsBuilder_ != null) {
        return videoActionRecognitionPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return videoActionRecognitionPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.getDefaultInstance() : videoActionRecognitionPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams video_action_recognition_prediction_params = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder> 
        getVideoActionRecognitionPredictionParamsFieldBuilder() {
      if (videoActionRecognitionPredictionParamsBuilder_ == null) {
        videoActionRecognitionPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoActionRecognitionPredictionParamsOrBuilder>(
                getVideoActionRecognitionPredictionParams(),
                getParentForChildren(),
                isClean());
        videoActionRecognitionPredictionParams_ = null;
      }
      return videoActionRecognitionPredictionParamsBuilder_;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams videoClassificationPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder> videoClassificationPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     * @return Whether the videoClassificationPredictionParams field is set.
     */
    public boolean hasVideoClassificationPredictionParams() {
      return videoClassificationPredictionParamsBuilder_ != null || videoClassificationPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     * @return The videoClassificationPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams getVideoClassificationPredictionParams() {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        return videoClassificationPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.getDefaultInstance() : videoClassificationPredictionParams_;
      } else {
        return videoClassificationPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public Builder setVideoClassificationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams value) {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoClassificationPredictionParams_ = value;
        onChanged();
      } else {
        videoClassificationPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public Builder setVideoClassificationPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder builderForValue) {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        videoClassificationPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        videoClassificationPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public Builder mergeVideoClassificationPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams value) {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        if (videoClassificationPredictionParams_ != null) {
          videoClassificationPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.newBuilder(videoClassificationPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          videoClassificationPredictionParams_ = value;
        }
        onChanged();
      } else {
        videoClassificationPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public Builder clearVideoClassificationPredictionParams() {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        videoClassificationPredictionParams_ = null;
        onChanged();
      } else {
        videoClassificationPredictionParams_ = null;
        videoClassificationPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder getVideoClassificationPredictionParamsBuilder() {
      
      onChanged();
      return getVideoClassificationPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder getVideoClassificationPredictionParamsOrBuilder() {
      if (videoClassificationPredictionParamsBuilder_ != null) {
        return videoClassificationPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return videoClassificationPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.getDefaultInstance() : videoClassificationPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams video_classification_prediction_params = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder> 
        getVideoClassificationPredictionParamsFieldBuilder() {
      if (videoClassificationPredictionParamsBuilder_ == null) {
        videoClassificationPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoClassificationPredictionParamsOrBuilder>(
                getVideoClassificationPredictionParams(),
                getParentForChildren(),
                isClean());
        videoClassificationPredictionParams_ = null;
      }
      return videoClassificationPredictionParamsBuilder_;
    }

    private com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams videoObjectTrackingPredictionParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder> videoObjectTrackingPredictionParamsBuilder_;
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     * @return Whether the videoObjectTrackingPredictionParams field is set.
     */
    public boolean hasVideoObjectTrackingPredictionParams() {
      return videoObjectTrackingPredictionParamsBuilder_ != null || videoObjectTrackingPredictionParams_ != null;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     * @return The videoObjectTrackingPredictionParams.
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams getVideoObjectTrackingPredictionParams() {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        return videoObjectTrackingPredictionParams_ == null ? com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.getDefaultInstance() : videoObjectTrackingPredictionParams_;
      } else {
        return videoObjectTrackingPredictionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public Builder setVideoObjectTrackingPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams value) {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoObjectTrackingPredictionParams_ = value;
        onChanged();
      } else {
        videoObjectTrackingPredictionParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public Builder setVideoObjectTrackingPredictionParams(
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder builderForValue) {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        videoObjectTrackingPredictionParams_ = builderForValue.build();
        onChanged();
      } else {
        videoObjectTrackingPredictionParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public Builder mergeVideoObjectTrackingPredictionParams(com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams value) {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        if (videoObjectTrackingPredictionParams_ != null) {
          videoObjectTrackingPredictionParams_ =
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.newBuilder(videoObjectTrackingPredictionParams_).mergeFrom(value).buildPartial();
        } else {
          videoObjectTrackingPredictionParams_ = value;
        }
        onChanged();
      } else {
        videoObjectTrackingPredictionParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public Builder clearVideoObjectTrackingPredictionParams() {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        videoObjectTrackingPredictionParams_ = null;
        onChanged();
      } else {
        videoObjectTrackingPredictionParams_ = null;
        videoObjectTrackingPredictionParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder getVideoObjectTrackingPredictionParamsBuilder() {
      
      onChanged();
      return getVideoObjectTrackingPredictionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    public com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder getVideoObjectTrackingPredictionParamsOrBuilder() {
      if (videoObjectTrackingPredictionParamsBuilder_ != null) {
        return videoObjectTrackingPredictionParamsBuilder_.getMessageOrBuilder();
      } else {
        return videoObjectTrackingPredictionParams_ == null ?
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.getDefaultInstance() : videoObjectTrackingPredictionParams_;
      }
    }
    /**
     * <code>.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams video_object_tracking_prediction_params = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder> 
        getVideoObjectTrackingPredictionParamsFieldBuilder() {
      if (videoObjectTrackingPredictionParamsBuilder_ == null) {
        videoObjectTrackingPredictionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParams.Builder, com.google.cloud.aiplatform.v1beta1.schema.predict.params.VideoObjectTrackingPredictionParamsOrBuilder>(
                getVideoObjectTrackingPredictionParams(),
                getParentForChildren(),
                isClean());
        videoObjectTrackingPredictionParams_ = null;
      }
      return videoObjectTrackingPredictionParamsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.cloud.aiplatform.v1beta1.PredictParams)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.aiplatform.v1beta1.PredictParams)
  private static final com.google.cloud.aiplatform.v1beta1.PredictParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.aiplatform.v1beta1.PredictParams();
  }

  public static com.google.cloud.aiplatform.v1beta1.PredictParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictParams>
      PARSER = new com.google.protobuf.AbstractParser<PredictParams>() {
    @java.lang.Override
    public PredictParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PredictParams(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PredictParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.aiplatform.v1beta1.PredictParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

