// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/enhanced_types.proto

package com.google.cloud.aiplatform.v1beta1;

public interface PredictionResultsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.aiplatform.v1beta1.PredictionResults)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResult classification_prediction_result = 1;</code>
   * @return Whether the classificationPredictionResult field is set.
   */
  boolean hasClassificationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResult classification_prediction_result = 1;</code>
   * @return The classificationPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResult getClassificationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResult classification_prediction_result = 1;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ClassificationPredictionResultOrBuilder getClassificationPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResult image_object_detection_result = 2;</code>
   * @return Whether the imageObjectDetectionResult field is set.
   */
  boolean hasImageObjectDetectionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResult image_object_detection_result = 2;</code>
   * @return The imageObjectDetectionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResult getImageObjectDetectionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResult image_object_detection_result = 2;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageObjectDetectionPredictionResultOrBuilder getImageObjectDetectionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResult image_segmentation_prediction_result = 3;</code>
   * @return Whether the imageSegmentationPredictionResult field is set.
   */
  boolean hasImageSegmentationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResult image_segmentation_prediction_result = 3;</code>
   * @return The imageSegmentationPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResult getImageSegmentationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResult image_segmentation_prediction_result = 3;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.ImageSegmentationPredictionResultOrBuilder getImageSegmentationPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResult tabular_classification_prediction_result = 4;</code>
   * @return Whether the tabularClassificationPredictionResult field is set.
   */
  boolean hasTabularClassificationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResult tabular_classification_prediction_result = 4;</code>
   * @return The tabularClassificationPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResult getTabularClassificationPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResult tabular_classification_prediction_result = 4;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularClassificationPredictionResultOrBuilder getTabularClassificationPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResult tabular_regression_prediction_result = 5;</code>
   * @return Whether the tabularRegressionPredictionResult field is set.
   */
  boolean hasTabularRegressionPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResult tabular_regression_prediction_result = 5;</code>
   * @return The tabularRegressionPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResult getTabularRegressionPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResult tabular_regression_prediction_result = 5;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TabularRegressionPredictionResultOrBuilder getTabularRegressionPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResult text_extraction_prediction_result = 6;</code>
   * @return Whether the textExtractionPredictionResult field is set.
   */
  boolean hasTextExtractionPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResult text_extraction_prediction_result = 6;</code>
   * @return The textExtractionPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResult getTextExtractionPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResult text_extraction_prediction_result = 6;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextExtractionPredictionResultOrBuilder getTextExtractionPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResult text_sentiment_prediction_result = 7;</code>
   * @return Whether the textSentimentPredictionResult field is set.
   */
  boolean hasTextSentimentPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResult text_sentiment_prediction_result = 7;</code>
   * @return The textSentimentPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResult getTextSentimentPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResult text_sentiment_prediction_result = 7;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TextSentimentPredictionResultOrBuilder getTextSentimentPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResult time_series_forecasting_prediction_result = 8;</code>
   * @return Whether the timeSeriesForecastingPredictionResult field is set.
   */
  boolean hasTimeSeriesForecastingPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResult time_series_forecasting_prediction_result = 8;</code>
   * @return The timeSeriesForecastingPredictionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResult getTimeSeriesForecastingPredictionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResult time_series_forecasting_prediction_result = 8;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.TimeSeriesForecastingPredictionResultOrBuilder getTimeSeriesForecastingPredictionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResult video_action_recognition_result = 9;</code>
   * @return Whether the videoActionRecognitionResult field is set.
   */
  boolean hasVideoActionRecognitionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResult video_action_recognition_result = 9;</code>
   * @return The videoActionRecognitionResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResult getVideoActionRecognitionResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResult video_action_recognition_result = 9;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoActionRecognitionPredictionResultOrBuilder getVideoActionRecognitionResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_classification_result = 10;</code>
   * @return Whether the videoClassificationResult field is set.
   */
  boolean hasVideoClassificationResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_classification_result = 10;</code>
   * @return The videoClassificationResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult getVideoClassificationResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_classification_result = 10;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResultOrBuilder getVideoClassificationResultOrBuilder();

  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_object_tracking_result = 11;</code>
   * @return Whether the videoObjectTrackingResult field is set.
   */
  boolean hasVideoObjectTrackingResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_object_tracking_result = 11;</code>
   * @return The videoObjectTrackingResult.
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult getVideoObjectTrackingResult();
  /**
   * <code>.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResult video_object_tracking_result = 11;</code>
   */
  com.google.cloud.aiplatform.v1beta1.schema.predict.prediction.VideoClassificationPredictionResultOrBuilder getVideoObjectTrackingResultOrBuilder();
}
