// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/explanation.proto

package com.google.cloud.aiplatform.v1beta1;

public interface SimilarityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.aiplatform.v1beta1.Similarity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Cloud Storage location for the input instances.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1beta1.GcsSource gcs_source = 1;</code>
   * @return Whether the gcsSource field is set.
   */
  boolean hasGcsSource();
  /**
   * <pre>
   * The Cloud Storage location for the input instances.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1beta1.GcsSource gcs_source = 1;</code>
   * @return The gcsSource.
   */
  com.google.cloud.aiplatform.v1beta1.GcsSource getGcsSource();
  /**
   * <pre>
   * The Cloud Storage location for the input instances.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1beta1.GcsSource gcs_source = 1;</code>
   */
  com.google.cloud.aiplatform.v1beta1.GcsSourceOrBuilder getGcsSourceOrBuilder();

  /**
   * <pre>
   * The configuration for the generated index, the semantics are the same as
   * [metadata][google.cloud.aiplatform.v1beta1.Index.metadata] and should match NearestNeighborSearchConfig.
   * </pre>
   *
   * <code>.google.protobuf.Value nearest_neighbor_search_config = 2;</code>
   * @return Whether the nearestNeighborSearchConfig field is set.
   */
  boolean hasNearestNeighborSearchConfig();
  /**
   * <pre>
   * The configuration for the generated index, the semantics are the same as
   * [metadata][google.cloud.aiplatform.v1beta1.Index.metadata] and should match NearestNeighborSearchConfig.
   * </pre>
   *
   * <code>.google.protobuf.Value nearest_neighbor_search_config = 2;</code>
   * @return The nearestNeighborSearchConfig.
   */
  com.google.protobuf.Value getNearestNeighborSearchConfig();
  /**
   * <pre>
   * The configuration for the generated index, the semantics are the same as
   * [metadata][google.cloud.aiplatform.v1beta1.Index.metadata] and should match NearestNeighborSearchConfig.
   * </pre>
   *
   * <code>.google.protobuf.Value nearest_neighbor_search_config = 2;</code>
   */
  com.google.protobuf.ValueOrBuilder getNearestNeighborSearchConfigOrBuilder();
}
