// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/value.proto

package com.google.cloud.aiplatform.v1beta1;

public final class ValueProto {
  private ValueProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_aiplatform_v1beta1_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+google/cloud/aiplatform/v1beta1/value." +
      "proto\022\037google.cloud.aiplatform.v1beta1\032\034" +
      "google/api/annotations.proto\"U\n\005Value\022\023\n" +
      "\tint_value\030\001 \001(\003H\000\022\026\n\014double_value\030\002 \001(\001" +
      "H\000\022\026\n\014string_value\030\003 \001(\tH\000B\007\n\005valueB~\n#c" +
      "om.google.cloud.aiplatform.v1beta1B\nValu" +
      "eProtoP\001ZIgoogle.golang.org/genproto/goo" +
      "gleapis/cloud/aiplatform/v1beta1;aiplatf" +
      "ormb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_cloud_aiplatform_v1beta1_Value_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1beta1_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_aiplatform_v1beta1_Value_descriptor,
        new java.lang.String[] { "IntValue", "DoubleValue", "StringValue", "Value", });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
