/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/batch_prediction_job.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class BatchPredictionJobProto {
  private BatchPredictionJobProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_InputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_InputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ManualBatchTuningParameters_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ManualBatchTuningParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n;google/cloud/aiplatform/v1alpha1/batch"
          + "_prediction_job.proto\022 google.cloud.aipl"
          + "atform.v1alpha1\032\037google/api/field_behavi"
          + "or.proto\032\031google/api/resource.proto\0327goo"
          + "gle/cloud/aiplatform/v1alpha1/completion"
          + "_stats.proto\032)google/cloud/aiplatform/v1"
          + "alpha1/io.proto\0320google/cloud/aiplatform"
          + "/v1alpha1/job_state.proto\0328google/cloud/"
          + "aiplatform/v1alpha1/machine_resources.pr"
          + "oto\032\034google/protobuf/struct.proto\032\037googl"
          + "e/protobuf/timestamp.proto\032\027google/rpc/s"
          + "tatus.proto\032\034google/api/annotations.prot"
          + "o\"\342\017\n\022BatchPredictionJob\022\021\n\004name\030\001 \001(\tB\003"
          + "\340A\003\022\031\n\014display_name\030\002 \001(\tB\003\340A\002\0226\n\005model\030"
          + "\003 \001(\tB\'\340A\002\372A!\n\037aiplatform.googleapis.com"
          + "/Model\022[\n\014input_config\030\004 \001(\0132@.google.cl"
          + "oud.aiplatform.v1alpha1.BatchPredictionJ"
          + "ob.InputConfigB\003\340A\002\0220\n\020model_parameters\030"
          + "\005 \001(\0132\026.google.protobuf.Value\022]\n\routput_"
          + "config\030\006 \001(\0132A.google.cloud.aiplatform.v"
          + "1alpha1.BatchPredictionJob.OutputConfigB"
          + "\003\340A\002\022V\n\023dedicated_resources\030\007 \001(\01329.goog"
          + "le.cloud.aiplatform.v1alpha1.BatchDedica"
          + "tedResources\022j\n\036manual_batch_tuning_para"
          + "meters\030\010 \001(\0132=.google.cloud.aiplatform.v"
          + "1alpha1.ManualBatchTuningParametersB\003\340A\005"
          + "\022\034\n\024generate_explanation\030\027 \001(\010\022Y\n\013output"
          + "_info\030\t \001(\0132?.google.cloud.aiplatform.v1"
          + "alpha1.BatchPredictionJob.OutputInfoB\003\340A"
          + "\003\022>\n\005state\030\n \001(\0162*.google.cloud.aiplatfo"
          + "rm.v1alpha1.JobStateB\003\340A\003\022&\n\005error\030\013 \001(\013"
          + "2\022.google.rpc.StatusB\003\340A\003\0221\n\020partial_fai"
          + "lures\030\014 \003(\0132\022.google.rpc.StatusB\003\340A\003\022T\n\022"
          + "resources_consumed\030\r \001(\01323.google.cloud."
          + "aiplatform.v1alpha1.ResourcesConsumedB\003\340"
          + "A\003\022P\n\020completion_stats\030\016 \001(\01321.google.cl"
          + "oud.aiplatform.v1alpha1.CompletionStatsB"
          + "\003\340A\003\0224\n\013create_time\030\017 \001(\0132\032.google.proto"
          + "buf.TimestampB\003\340A\003\0223\n\nstart_time\030\020 \001(\0132\032"
          + ".google.protobuf.TimestampB\003\340A\003\0221\n\010end_t"
          + "ime\030\021 \001(\0132\032.google.protobuf.TimestampB\003\340"
          + "A\003\0224\n\013update_time\030\022 \001(\0132\032.google.protobu"
          + "f.TimestampB\003\340A\003\022P\n\006labels\030\023 \003(\0132@.googl"
          + "e.cloud.aiplatform.v1alpha1.BatchPredict"
          + "ionJob.LabelsEntry\032\306\001\n\013InputConfig\022A\n\ngc"
          + "s_source\030\002 \001(\0132+.google.cloud.aiplatform"
          + ".v1alpha1.GcsSourceH\000\022K\n\017bigquery_source"
          + "\030\003 \001(\01320.google.cloud.aiplatform.v1alpha"
          + "1.BigQuerySourceH\000\022\035\n\020instances_format\030\001"
          + " \001(\tB\003\340A\002B\010\n\006source\032\342\001\n\014OutputConfig\022K\n\017"
          + "gcs_destination\030\002 \001(\01320.google.cloud.aip"
          + "latform.v1alpha1.GcsDestinationH\000\022U\n\024big"
          + "query_destination\030\003 \001(\01325.google.cloud.a"
          + "iplatform.v1alpha1.BigQueryDestinationH\000"
          + "\022\037\n\022predictions_format\030\001 \001(\tB\003\340A\002B\r\n\013des"
          + "tination\032l\n\nOutputInfo\022#\n\024gcs_output_dir"
          + "ectory\030\001 \001(\tB\003\340A\003H\000\022&\n\027bigquery_output_d"
          + "ataset\030\002 \001(\tB\003\340A\003H\000B\021\n\017output_location\032-"
          + "\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
          + "\t:\0028\001:\206\001\352A\202\001\n,aiplatform.googleapis.com/"
          + "BatchPredictionJob\022Rprojects/{project}/l"
          + "ocations/{location}/batchPredictionJobs/"
          + "{batch_prediction_job}\"6\n\033ManualBatchTun"
          + "ingParameters\022\027\n\nbatch_size\030\001 \001(\005B\003\340A\005B\215"
          + "\001\n$com.google.cloud.aiplatform.v1alpha1B"
          + "\027BatchPredictionJobProtoP\001ZJgoogle.golan"
          + "g.org/genproto/googleapis/cloud/aiplatfo"
          + "rm/v1alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.CompletionStatsProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.IoProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.JobStateProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.MachineResourcesProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Model",
              "InputConfig",
              "ModelParameters",
              "OutputConfig",
              "DedicatedResources",
              "ManualBatchTuningParameters",
              "GenerateExplanation",
              "OutputInfo",
              "State",
              "Error",
              "PartialFailures",
              "ResourcesConsumed",
              "CompletionStats",
              "CreateTime",
              "StartTime",
              "EndTime",
              "UpdateTime",
              "Labels",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_InputConfig_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_InputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_InputConfig_descriptor,
            new java.lang.String[] {
              "GcsSource", "BigquerySource", "InstancesFormat", "Source",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputConfig_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputConfig_descriptor,
            new java.lang.String[] {
              "GcsDestination", "BigqueryDestination", "PredictionsFormat", "Destination",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputInfo_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_OutputInfo_descriptor,
            new java.lang.String[] {
              "GcsOutputDirectory", "BigqueryOutputDataset", "OutputLocation",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_LabelsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_BatchPredictionJob_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ManualBatchTuningParameters_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_ManualBatchTuningParameters_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ManualBatchTuningParameters_descriptor,
            new java.lang.String[] {
              "BatchSize",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.CompletionStatsProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.IoProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.JobStateProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.MachineResourcesProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
