/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/dataset_service.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class DatasetServiceProto {
  private DatasetServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetDatasetRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetDatasetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UpdateDatasetRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UpdateDatasetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteDatasetRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteDatasetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ImportDataOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportDataOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetAnnotationSpecRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetAnnotationSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n6google/cloud/aiplatform/v1alpha1/datas"
          + "et_service.proto\022 google.cloud.aiplatfor"
          + "m.v1alpha1\032\034google/api/annotations.proto"
          + "\032\027google/api/client.proto\032\037google/api/fi"
          + "eld_behavior.proto\032\031google/api/resource."
          + "proto\0321google/cloud/aiplatform/v1alpha1/"
          + "annotation.proto\0326google/cloud/aiplatfor"
          + "m/v1alpha1/annotation_spec.proto\0320google"
          + "/cloud/aiplatform/v1alpha1/data_item.pro"
          + "to\032.google/cloud/aiplatform/v1alpha1/dat"
          + "aset.proto\0320google/cloud/aiplatform/v1al"
          + "pha1/operation.proto\032#google/longrunning"
          + "/operations.proto\032 google/protobuf/field"
          + "_mask.proto\"\222\001\n\024CreateDatasetRequest\0229\n\006"
          + "parent\030\001 \001(\tB)\340A\002\372A#\n!locations.googleap"
          + "is.com/Location\022?\n\007dataset\030\002 \001(\0132).googl"
          + "e.cloud.aiplatform.v1alpha1.DatasetB\003\340A\002"
          + "\"v\n\036CreateDatasetOperationMetadata\022T\n\020ge"
          + "neric_metadata\030\001 \001(\0132:.google.cloud.aipl"
          + "atform.v1alpha1.GenericOperationMetadata"
          + "\"{\n\021GetDatasetRequest\0227\n\004name\030\001 \001(\tB)\340A\002"
          + "\372A#\n!aiplatform.googleapis.com/Dataset\022-"
          + "\n\tread_mask\030\002 \001(\0132\032.google.protobuf.Fiel"
          + "dMask\"\215\001\n\024UpdateDatasetRequest\022?\n\007datase"
          + "t\030\001 \001(\0132).google.cloud.aiplatform.v1alph"
          + "a1.DatasetB\003\340A\002\0224\n\013update_mask\030\002 \001(\0132\032.g"
          + "oogle.protobuf.FieldMaskB\003\340A\002\"\266\001\n\023ListDa"
          + "tasetsRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!l"
          + "ocations.googleapis.com/Location\022\016\n\006filt"
          + "er\030\002 \001(\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_toke"
          + "n\030\004 \001(\t\022-\n\tread_mask\030\005 \001(\0132\032.google.prot"
          + "obuf.FieldMask\"l\n\024ListDatasetsResponse\022;"
          + "\n\010datasets\030\001 \003(\0132).google.cloud.aiplatfo"
          + "rm.v1alpha1.Dataset\022\027\n\017next_page_token\030\002"
          + " \001(\t\"O\n\024DeleteDatasetRequest\0227\n\004name\030\001 \001"
          + "(\tB)\340A\002\372A#\n!aiplatform.googleapis.com/Da"
          + "taset\"\235\001\n\021ImportDataRequest\0227\n\004name\030\001 \001("
          + "\tB)\340A\002\372A#\n!aiplatform.googleapis.com/Dat"
          + "aset\022O\n\016import_configs\030\002 \003(\01322.google.cl"
          + "oud.aiplatform.v1alpha1.ImportDataConfig"
          + "B\003\340A\002\"\024\n\022ImportDataResponse\"s\n\033ImportDat"
          + "aOperationMetadata\022T\n\020generic_metadata\030\001"
          + " \001(\0132:.google.cloud.aiplatform.v1alpha1."
          + "GenericOperationMetadata\"\234\001\n\021ExportDataR"
          + "equest\0227\n\004name\030\001 \001(\tB)\340A\002\372A#\n!aiplatform"
          + ".googleapis.com/Dataset\022N\n\rexport_config"
          + "\030\002 \001(\01322.google.cloud.aiplatform.v1alpha"
          + "1.ExportDataConfigB\003\340A\002\",\n\022ExportDataRes"
          + "ponse\022\026\n\016exported_files\030\001 \003(\t\"\221\001\n\033Export"
          + "DataOperationMetadata\022T\n\020generic_metadat"
          + "a\030\001 \001(\0132:.google.cloud.aiplatform.v1alph"
          + "a1.GenericOperationMetadata\022\034\n\024gcs_outpu"
          + "t_directory\030\002 \001(\t\"\267\001\n\024ListDataItemsReque"
          + "st\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!aiplatform.g"
          + "oogleapis.com/Dataset\022\016\n\006filter\030\002 \001(\t\022\021\n"
          + "\tpage_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\022-\n\t"
          + "read_mask\030\005 \001(\0132\032.google.protobuf.FieldM"
          + "ask\"p\n\025ListDataItemsResponse\022>\n\ndata_ite"
          + "ms\030\001 \003(\0132*.google.cloud.aiplatform.v1alp"
          + "ha1.DataItem\022\027\n\017next_page_token\030\002 \001(\t\"\211\001"
          + "\n\030GetAnnotationSpecRequest\022>\n\004name\030\001 \001(\t"
          + "B0\340A\002\372A*\n(aiplatform.googleapis.com/Anno"
          + "tationSpec\022-\n\tread_mask\030\002 \001(\0132\032.google.p"
          + "rotobuf.FieldMask\"\272\001\n\026ListAnnotationsReq"
          + "uest\022:\n\006parent\030\001 \001(\tB*\340A\002\372A$\n\"aiplatform"
          + ".googleapis.com/DataItem\022\016\n\006filter\030\002 \001(\t"
          + "\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\022"
          + "-\n\tread_mask\030\005 \001(\0132\032.google.protobuf.Fie"
          + "ldMask\"u\n\027ListAnnotationsResponse\022A\n\013ann"
          + "otations\030\001 \003(\0132,.google.cloud.aiplatform"
          + ".v1alpha1.Annotation\022\027\n\017next_page_token\030"
          + "\002 \001(\t2\365\021\n\016DatasetService\022\351\001\n\rCreateDatas"
          + "et\0226.google.cloud.aiplatform.v1alpha1.Cr"
          + "eateDatasetRequest\032\035.google.longrunning."
          + "Operation\"\200\001\202\323\344\223\002=\"2/v1alpha1/{parent=pr"
          + "ojects/*/locations/*}/datasets:\007dataset\332"
          + "A\016parent,dataset\312A)\n\007Dataset\022\036CreateData"
          + "setOperationMetadata\022\257\001\n\nGetDataset\0223.go"
          + "ogle.cloud.aiplatform.v1alpha1.GetDatase"
          + "tRequest\032).google.cloud.aiplatform.v1alp"
          + "ha1.Dataset\"A\202\323\344\223\0024\0222/v1alpha1/{name=pro"
          + "jects/*/locations/*/datasets/*}\332A\004name\022\325"
          + "\001\n\rUpdateDataset\0226.google.cloud.aiplatfo"
          + "rm.v1alpha1.UpdateDatasetRequest\032).googl"
          + "e.cloud.aiplatform.v1alpha1.Dataset\"a\202\323\344"
          + "\223\002E2:/v1alpha1/{dataset.name=projects/*/"
          + "locations/*/datasets/*}:\007dataset\332A\023datas"
          + "et,update_mask\022\302\001\n\014ListDatasets\0225.google"
          + ".cloud.aiplatform.v1alpha1.ListDatasetsR"
          + "equest\0326.google.cloud.aiplatform.v1alpha"
          + "1.ListDatasetsResponse\"C\202\323\344\223\0024\0222/v1alpha"
          + "1/{parent=projects/*/locations/*}/datase"
          + "ts\332A\006parent\022\334\001\n\rDeleteDataset\0226.google.c"
          + "loud.aiplatform.v1alpha1.DeleteDatasetRe"
          + "quest\032\035.google.longrunning.Operation\"t\202\323"
          + "\344\223\0024*2/v1alpha1/{name=projects/*/locatio"
          + "ns/*/datasets/*}\332A\004name\312A0\n\025google.proto"
          + "buf.Empty\022\027DeleteOperationMetadata\022\361\001\n\nI"
          + "mportData\0223.google.cloud.aiplatform.v1al"
          + "pha1.ImportDataRequest\032\035.google.longrunn"
          + "ing.Operation\"\216\001\202\323\344\223\002>\"9/v1alpha1/{name="
          + "projects/*/locations/*/datasets/*}:impor"
          + "t:\001*\332A\023name,import_configs\312A1\n\022ImportDat"
          + "aResponse\022\033ImportDataOperationMetadata\022\360"
          + "\001\n\nExportData\0223.google.cloud.aiplatform."
          + "v1alpha1.ExportDataRequest\032\035.google.long"
          + "running.Operation\"\215\001\202\323\344\223\002>\"9/v1alpha1/{n"
          + "ame=projects/*/locations/*/datasets/*}:e"
          + "xport:\001*\332A\022name,export_config\312A1\n\022Export"
          + "DataResponse\022\033ExportDataOperationMetadat"
          + "a\022\321\001\n\rListDataItems\0226.google.cloud.aipla"
          + "tform.v1alpha1.ListDataItemsRequest\0327.go"
          + "ogle.cloud.aiplatform.v1alpha1.ListDataI"
          + "temsResponse\"O\202\323\344\223\002@\022>/v1alpha1/{parent="
          + "projects/*/locations/*/datasets/*}/dataI"
          + "tems\332A\006parent\022\326\001\n\021GetAnnotationSpec\022:.go"
          + "ogle.cloud.aiplatform.v1alpha1.GetAnnota"
          + "tionSpecRequest\0320.google.cloud.aiplatfor"
          + "m.v1alpha1.AnnotationSpec\"S\202\323\344\223\002F\022D/v1al"
          + "pha1/{name=projects/*/locations/*/datase"
          + "ts/*/annotationSpecs/*}\332A\004name\022\345\001\n\017ListA"
          + "nnotations\0228.google.cloud.aiplatform.v1a"
          + "lpha1.ListAnnotationsRequest\0329.google.cl"
          + "oud.aiplatform.v1alpha1.ListAnnotationsR"
          + "esponse\"]\202\323\344\223\002N\022L/v1alpha1/{parent=proje"
          + "cts/*/locations/*/datasets/*/dataItems/*"
          + "}/annotations\332A\006parent\032M\312A\031aiplatform.go"
          + "ogleapis.com\322A.https://www.googleapis.co"
          + "m/auth/cloud-platformB\211\001\n$com.google.clo"
          + "ud.aiplatform.v1alpha1B\023DatasetServicePr"
          + "otoP\001ZJgoogle.golang.org/genproto/google"
          + "apis/cloud/aiplatform/v1alpha1;aiplatfor"
          + "mb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.AnnotationProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.AnnotationSpecProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.DataItemProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.DatasetProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Dataset",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_CreateDatasetOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_GetDatasetRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_GetDatasetRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetDatasetRequest_descriptor,
            new java.lang.String[] {
              "Name", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UpdateDatasetRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_UpdateDatasetRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UpdateDatasetRequest_descriptor,
            new java.lang.String[] {
              "Dataset", "UpdateMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListDatasetsResponse_descriptor,
            new java.lang.String[] {
              "Datasets", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteDatasetRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteDatasetRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeleteDatasetRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ImportDataRequest_descriptor,
            new java.lang.String[] {
              "Name", "ImportConfigs",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataResponse_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ImportDataResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_aiplatform_v1alpha1_ImportDataOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ImportDataOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportDataRequest_descriptor,
            new java.lang.String[] {
              "Name", "ExportConfig",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportDataResponse_descriptor,
            new java.lang.String[] {
              "ExportedFiles",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportDataOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportDataOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata", "GcsOutputDirectory",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsResponse_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListDataItemsResponse_descriptor,
            new java.lang.String[] {
              "DataItems", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_GetAnnotationSpecRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_aiplatform_v1alpha1_GetAnnotationSpecRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetAnnotationSpecRequest_descriptor,
            new java.lang.String[] {
              "Name", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListAnnotationsResponse_descriptor,
            new java.lang.String[] {
              "Annotations", "NextPageToken",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.AnnotationProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.AnnotationSpecProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.DataItemProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.DatasetProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
