/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/endpoint_service.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class EndpointServiceProto {
  private EndpointServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetEndpointRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetEndpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UpdateEndpointRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UpdateEndpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteEndpointRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteEndpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_TrafficSplitEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_TrafficSplitEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeployModelOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_TrafficSplitEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_TrafficSplitEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelOperationMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n7google/cloud/aiplatform/v1alpha1/endpo"
          + "int_service.proto\022 google.cloud.aiplatfo"
          + "rm.v1alpha1\032\034google/api/annotations.prot"
          + "o\032\027google/api/client.proto\032\037google/api/f"
          + "ield_behavior.proto\032\031google/api/resource"
          + ".proto\032/google/cloud/aiplatform/v1alpha1"
          + "/endpoint.proto\0320google/cloud/aiplatform"
          + "/v1alpha1/operation.proto\032#google/longru"
          + "nning/operations.proto\032 google/protobuf/"
          + "field_mask.proto\"\225\001\n\025CreateEndpointReque"
          + "st\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!locations.go"
          + "ogleapis.com/Location\022A\n\010endpoint\030\002 \001(\0132"
          + "*.google.cloud.aiplatform.v1alpha1.Endpo"
          + "intB\003\340A\002\"w\n\037CreateEndpointOperationMetad"
          + "ata\022T\n\020generic_metadata\030\001 \001(\0132:.google.c"
          + "loud.aiplatform.v1alpha1.GenericOperatio"
          + "nMetadata\"N\n\022GetEndpointRequest\0228\n\004name\030"
          + "\001 \001(\tB*\340A\002\372A$\n\"aiplatform.googleapis.com"
          + "/Endpoint\"\313\001\n\024ListEndpointsRequest\0229\n\006pa"
          + "rent\030\001 \001(\tB)\340A\002\372A#\n!locations.googleapis"
          + ".com/Location\022\023\n\006filter\030\002 \001(\tB\003\340A\001\022\026\n\tpa"
          + "ge_size\030\003 \001(\005B\003\340A\001\022\027\n\npage_token\030\004 \001(\tB\003"
          + "\340A\001\0222\n\tread_mask\030\005 \001(\0132\032.google.protobuf"
          + ".FieldMaskB\003\340A\001\"o\n\025ListEndpointsResponse"
          + "\022=\n\tendpoints\030\001 \003(\0132*.google.cloud.aipla"
          + "tform.v1alpha1.Endpoint\022\027\n\017next_page_tok"
          + "en\030\002 \001(\t\"\220\001\n\025UpdateEndpointRequest\022A\n\010en"
          + "dpoint\030\001 \001(\0132*.google.cloud.aiplatform.v"
          + "1alpha1.EndpointB\003\340A\002\0224\n\013update_mask\030\002 \001"
          + "(\0132\032.google.protobuf.FieldMaskB\003\340A\002\"Q\n\025D"
          + "eleteEndpointRequest\0228\n\004name\030\001 \001(\tB*\340A\002\372"
          + "A$\n\"aiplatform.googleapis.com/Endpoint\"\264"
          + "\002\n\022DeployModelRequest\022<\n\010endpoint\030\001 \001(\tB"
          + "*\340A\002\372A$\n\"aiplatform.googleapis.com/Endpo"
          + "int\022L\n\016deployed_model\030\002 \001(\0132/.google.clo"
          + "ud.aiplatform.v1alpha1.DeployedModelB\003\340A"
          + "\002\022]\n\rtraffic_split\030\003 \003(\0132F.google.cloud."
          + "aiplatform.v1alpha1.DeployModelRequest.T"
          + "rafficSplitEntry\0323\n\021TrafficSplitEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"^\n\023DeployM"
          + "odelResponse\022G\n\016deployed_model\030\001 \001(\0132/.g"
          + "oogle.cloud.aiplatform.v1alpha1.Deployed"
          + "Model\"t\n\034DeployModelOperationMetadata\022T\n"
          + "\020generic_metadata\030\001 \001(\0132:.google.cloud.a"
          + "iplatform.v1alpha1.GenericOperationMetad"
          + "ata\"\212\002\n\024UndeployModelRequest\022<\n\010endpoint"
          + "\030\001 \001(\tB*\340A\002\372A$\n\"aiplatform.googleapis.co"
          + "m/Endpoint\022\036\n\021deployed_model_id\030\002 \001(\tB\003\340"
          + "A\002\022_\n\rtraffic_split\030\003 \003(\0132H.google.cloud"
          + ".aiplatform.v1alpha1.UndeployModelReques"
          + "t.TrafficSplitEntry\0323\n\021TrafficSplitEntry"
          + "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"\027\n\025Unde"
          + "ployModelResponse\"v\n\036UndeployModelOperat"
          + "ionMetadata\022T\n\020generic_metadata\030\001 \001(\0132:."
          + "google.cloud.aiplatform.v1alpha1.Generic"
          + "OperationMetadata2\310\r\n\017EndpointService\022\360\001"
          + "\n\016CreateEndpoint\0227.google.cloud.aiplatfo"
          + "rm.v1alpha1.CreateEndpointRequest\032\035.goog"
          + "le.longrunning.Operation\"\205\001\202\323\344\223\002?\"3/v1al"
          + "pha1/{parent=projects/*/locations/*}/end"
          + "points:\010endpoint\332A\017parent,endpoint\312A+\n\010E"
          + "ndpoint\022\037CreateEndpointOperationMetadata"
          + "\022\263\001\n\013GetEndpoint\0224.google.cloud.aiplatfo"
          + "rm.v1alpha1.GetEndpointRequest\032*.google."
          + "cloud.aiplatform.v1alpha1.Endpoint\"B\202\323\344\223"
          + "\0025\0223/v1alpha1/{name=projects/*/locations"
          + "/*/endpoints/*}\332A\004name\022\306\001\n\rListEndpoints"
          + "\0226.google.cloud.aiplatform.v1alpha1.List"
          + "EndpointsRequest\0327.google.cloud.aiplatfo"
          + "rm.v1alpha1.ListEndpointsResponse\"D\202\323\344\223\002"
          + "5\0223/v1alpha1/{parent=projects/*/location"
          + "s/*}/endpoints\332A\006parent\022\334\001\n\016UpdateEndpoi"
          + "nt\0227.google.cloud.aiplatform.v1alpha1.Up"
          + "dateEndpointRequest\032*.google.cloud.aipla"
          + "tform.v1alpha1.Endpoint\"e\202\323\344\223\002H2</v1alph"
          + "a1/{endpoint.name=projects/*/locations/*"
          + "/endpoints/*}:\010endpoint\332A\024endpoint,updat"
          + "e_mask\022\337\001\n\016DeleteEndpoint\0227.google.cloud"
          + ".aiplatform.v1alpha1.DeleteEndpointReque"
          + "st\032\035.google.longrunning.Operation\"u\202\323\344\223\002"
          + "5*3/v1alpha1/{name=projects/*/locations/"
          + "*/endpoints/*}\332A\004name\312A0\n\025google.protobu"
          + "f.Empty\022\027DeleteOperationMetadata\022\221\002\n\013Dep"
          + "loyModel\0224.google.cloud.aiplatform.v1alp"
          + "ha1.DeployModelRequest\032\035.google.longrunn"
          + "ing.Operation\"\254\001\202\323\344\223\002H\"C/v1alpha1/{endpo"
          + "int=projects/*/locations/*/endpoints/*}:"
          + "deployModel:\001*\332A%endpoint,deployed_model"
          + ",traffic_split\312A3\n\023DeployModelResponse\022\034"
          + "DeployModelOperationMetadata\022\236\002\n\rUndeplo"
          + "yModel\0226.google.cloud.aiplatform.v1alpha"
          + "1.UndeployModelRequest\032\035.google.longrunn"
          + "ing.Operation\"\265\001\202\323\344\223\002J\"E/v1alpha1/{endpo"
          + "int=projects/*/locations/*/endpoints/*}:"
          + "undeployModel:\001*\332A(endpoint,deployed_mod"
          + "el_id,traffic_split\312A7\n\025UndeployModelRes"
          + "ponse\022\036UndeployModelOperationMetadata\032M\312"
          + "A\031aiplatform.googleapis.com\322A.https://ww"
          + "w.googleapis.com/auth/cloud-platformB\212\001\n"
          + "$com.google.cloud.aiplatform.v1alpha1B\024E"
          + "ndpointServiceProtoP\001ZJgoogle.golang.org"
          + "/genproto/googleapis/cloud/aiplatform/v1"
          + "alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.EndpointProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Endpoint",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_CreateEndpointOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_GetEndpointRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_GetEndpointRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetEndpointRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsResponse_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListEndpointsResponse_descriptor,
            new java.lang.String[] {
              "Endpoints", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UpdateEndpointRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_aiplatform_v1alpha1_UpdateEndpointRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UpdateEndpointRequest_descriptor,
            new java.lang.String[] {
              "Endpoint", "UpdateMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteEndpointRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteEndpointRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeleteEndpointRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_descriptor,
            new java.lang.String[] {
              "Endpoint", "DeployedModel", "TrafficSplit",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_TrafficSplitEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_TrafficSplitEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeployModelRequest_TrafficSplitEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelResponse_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeployModelResponse_descriptor,
            new java.lang.String[] {
              "DeployedModel",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_aiplatform_v1alpha1_DeployModelOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeployModelOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_descriptor,
            new java.lang.String[] {
              "Endpoint", "DeployedModelId", "TrafficSplit",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_TrafficSplitEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_TrafficSplitEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelRequest_TrafficSplitEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UndeployModelOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.EndpointProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
