/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/endpoint.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class EndpointProto {
  private EndpointProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_TrafficSplitEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_TrafficSplitEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeployedModel_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeployedModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n/google/cloud/aiplatform/v1alpha1/endpo"
          + "int.proto\022 google.cloud.aiplatform.v1alp"
          + "ha1\032\037google/api/field_behavior.proto\032\031go"
          + "ogle/api/resource.proto\0322google/cloud/ai"
          + "platform/v1alpha1/explanation.proto\0328goo"
          + "gle/cloud/aiplatform/v1alpha1/machine_re"
          + "sources.proto\032\037google/protobuf/timestamp"
          + ".proto\032\034google/api/annotations.proto\"\376\004\n"
          + "\010Endpoint\022\021\n\004name\030\001 \001(\tB\003\340A\003\022\031\n\014display_"
          + "name\030\002 \001(\tB\003\340A\002\022\023\n\013description\030\003 \001(\t\022M\n\017"
          + "deployed_models\030\004 \003(\0132/.google.cloud.aip"
          + "latform.v1alpha1.DeployedModelB\003\340A\003\022S\n\rt"
          + "raffic_split\030\005 \003(\0132<.google.cloud.aiplat"
          + "form.v1alpha1.Endpoint.TrafficSplitEntry"
          + "\022\014\n\004etag\030\006 \001(\t\022F\n\006labels\030\007 \003(\01326.google."
          + "cloud.aiplatform.v1alpha1.Endpoint.Label"
          + "sEntry\0224\n\013create_time\030\010 \001(\0132\032.google.pro"
          + "tobuf.TimestampB\003\340A\003\0224\n\013update_time\030\t \001("
          + "\0132\032.google.protobuf.TimestampB\003\340A\003\0323\n\021Tr"
          + "afficSplitEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
          + "\001(\005:\0028\001\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v"
          + "alue\030\002 \001(\t:\0028\001:e\352Ab\n\"aiplatform.googleap"
          + "is.com/Endpoint\022<projects/{project}/loca"
          + "tions/{location}/endpoints/{endpoint}\"\263\003"
          + "\n\rDeployedModel\022S\n\023dedicated_resources\030\007"
          + " \001(\01324.google.cloud.aiplatform.v1alpha1."
          + "DedicatedResourcesH\000\022S\n\023automatic_resour"
          + "ces\030\010 \001(\01324.google.cloud.aiplatform.v1al"
          + "pha1.AutomaticResourcesH\000\022\017\n\002id\030\001 \001(\tB\003\340"
          + "A\003\0226\n\005model\030\002 \001(\tB\'\340A\002\372A!\n\037aiplatform.go"
          + "ogleapis.com/Model\022\024\n\014display_name\030\003 \001(\t"
          + "\0224\n\013create_time\030\006 \001(\0132\032.google.protobuf."
          + "TimestampB\003\340A\003\022K\n\020explanation_spec\030\t \001(\013"
          + "21.google.cloud.aiplatform.v1alpha1.Expl"
          + "anationSpecB\026\n\024prediction_resourcesB\203\001\n$"
          + "com.google.cloud.aiplatform.v1alpha1B\rEn"
          + "dpointProtoP\001ZJgoogle.golang.org/genprot"
          + "o/googleapis/cloud/aiplatform/v1alpha1;a"
          + "iplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ExplanationProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.MachineResourcesProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "DeployedModels",
              "TrafficSplit",
              "Etag",
              "Labels",
              "CreateTime",
              "UpdateTime",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_TrafficSplitEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_TrafficSplitEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_TrafficSplitEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_LabelsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Endpoint_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeployedModel_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_DeployedModel_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeployedModel_descriptor,
            new java.lang.String[] {
              "DedicatedResources",
              "AutomaticResources",
              "Id",
              "Model",
              "DisplayName",
              "CreateTime",
              "ExplanationSpec",
              "PredictionResources",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ExplanationProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.MachineResourcesProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
