/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/explanation_metadata.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class ExplanationMetadataProto {
  private ExplanationMetadataProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n;google/cloud/aiplatform/v1alpha1/expla"
          + "nation_metadata.proto\022 google.cloud.aipl"
          + "atform.v1alpha1\032\037google/api/field_behavi"
          + "or.proto\032\034google/protobuf/struct.proto\032\034"
          + "google/api/annotations.proto\"\251\005\n\023Explana"
          + "tionMetadata\022V\n\006inputs\030\001 \003(\0132A.google.cl"
          + "oud.aiplatform.v1alpha1.ExplanationMetad"
          + "ata.InputsEntryB\003\340A\002\022X\n\007outputs\030\002 \003(\0132B."
          + "google.cloud.aiplatform.v1alpha1.Explana"
          + "tionMetadata.OutputsEntryB\003\340A\002\022\'\n\037featur"
          + "e_attributions_schema_uri\030\003 \001(\t\032@\n\rInput"
          + "Metadata\022/\n\017input_baselines\030\001 \003(\0132\026.goog"
          + "le.protobuf.Value\032\212\001\n\016OutputMetadata\022<\n\032"
          + "index_display_name_mapping\030\001 \001(\0132\026.googl"
          + "e.protobuf.ValueH\000\022\"\n\030display_name_mappi"
          + "ng_key\030\002 \001(\tH\000B\026\n\024display_name_mapping\032r"
          + "\n\013InputsEntry\022\013\n\003key\030\001 \001(\t\022R\n\005value\030\002 \001("
          + "\0132C.google.cloud.aiplatform.v1alpha1.Exp"
          + "lanationMetadata.InputMetadata:\0028\001\032t\n\014Ou"
          + "tputsEntry\022\013\n\003key\030\001 \001(\t\022S\n\005value\030\002 \001(\0132D"
          + ".google.cloud.aiplatform.v1alpha1.Explan"
          + "ationMetadata.OutputMetadata:\0028\001B\216\001\n$com"
          + ".google.cloud.aiplatform.v1alpha1B\030Expla"
          + "nationMetadataProtoP\001ZJgoogle.golang.org"
          + "/genproto/googleapis/cloud/aiplatform/v1"
          + "alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor,
            new java.lang.String[] {
              "Inputs", "Outputs", "FeatureAttributionsSchemaUri",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputMetadata_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputMetadata_descriptor,
            new java.lang.String[] {
              "InputBaselines",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputMetadata_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputMetadata_descriptor,
            new java.lang.String[] {
              "IndexDisplayNameMapping", "DisplayNameMappingKey", "DisplayNameMapping",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_InputsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExplanationMetadata_OutputsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
