/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/training_pipeline.proto

package com.google.cloud.aiplatform.v1alpha1;

public interface InputDataConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.aiplatform.v1alpha1.InputDataConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Split based on fractions defining the size of each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FractionSplit fraction_split = 2;</code>
   *
   * @return Whether the fractionSplit field is set.
   */
  boolean hasFractionSplit();
  /**
   *
   *
   * <pre>
   * Split based on fractions defining the size of each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FractionSplit fraction_split = 2;</code>
   *
   * @return The fractionSplit.
   */
  com.google.cloud.aiplatform.v1alpha1.FractionSplit getFractionSplit();
  /**
   *
   *
   * <pre>
   * Split based on fractions defining the size of each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FractionSplit fraction_split = 2;</code>
   */
  com.google.cloud.aiplatform.v1alpha1.FractionSplitOrBuilder getFractionSplitOrBuilder();

  /**
   *
   *
   * <pre>
   * Split based on the provided filters for each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FilterSplit filter_split = 3;</code>
   *
   * @return Whether the filterSplit field is set.
   */
  boolean hasFilterSplit();
  /**
   *
   *
   * <pre>
   * Split based on the provided filters for each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FilterSplit filter_split = 3;</code>
   *
   * @return The filterSplit.
   */
  com.google.cloud.aiplatform.v1alpha1.FilterSplit getFilterSplit();
  /**
   *
   *
   * <pre>
   * Split based on the provided filters for each set.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.FilterSplit filter_split = 3;</code>
   */
  com.google.cloud.aiplatform.v1alpha1.FilterSplitOrBuilder getFilterSplitOrBuilder();

  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on a predefined key.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.PredefinedSplit predefined_split = 4;</code>
   *
   * @return Whether the predefinedSplit field is set.
   */
  boolean hasPredefinedSplit();
  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on a predefined key.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.PredefinedSplit predefined_split = 4;</code>
   *
   * @return The predefinedSplit.
   */
  com.google.cloud.aiplatform.v1alpha1.PredefinedSplit getPredefinedSplit();
  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on a predefined key.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.PredefinedSplit predefined_split = 4;</code>
   */
  com.google.cloud.aiplatform.v1alpha1.PredefinedSplitOrBuilder getPredefinedSplitOrBuilder();

  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on the timestamp of the input data pieces.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.TimestampSplit timestamp_split = 5;</code>
   *
   * @return Whether the timestampSplit field is set.
   */
  boolean hasTimestampSplit();
  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on the timestamp of the input data pieces.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.TimestampSplit timestamp_split = 5;</code>
   *
   * @return The timestampSplit.
   */
  com.google.cloud.aiplatform.v1alpha1.TimestampSplit getTimestampSplit();
  /**
   *
   *
   * <pre>
   * Only supported for structured Datasets.
   * Split based on the timestamp of the input data pieces.
   * </pre>
   *
   * <code>.google.cloud.aiplatform.v1alpha1.TimestampSplit timestamp_split = 5;</code>
   */
  com.google.cloud.aiplatform.v1alpha1.TimestampSplitOrBuilder getTimestampSplitOrBuilder();

  /**
   *
   *
   * <pre>
   * Required. The ID of the Dataset in the same Project and Location which data will be
   * used to train the Model. The Dataset must use schema compatible with
   * Model being trained, and what is compatible should be described in the
   * used TrainingPipeline's [training_task_definition]
   * [google.cloud.aiplatform.v1alpha1.TrainingPipeline.training_task_definition].
   * For structured Datasets, all their data is exported to training, to pick
   * and choose from.
   * </pre>
   *
   * <code>string dataset_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The datasetId.
   */
  java.lang.String getDatasetId();
  /**
   *
   *
   * <pre>
   * Required. The ID of the Dataset in the same Project and Location which data will be
   * used to train the Model. The Dataset must use schema compatible with
   * Model being trained, and what is compatible should be described in the
   * used TrainingPipeline's [training_task_definition]
   * [google.cloud.aiplatform.v1alpha1.TrainingPipeline.training_task_definition].
   * For structured Datasets, all their data is exported to training, to pick
   * and choose from.
   * </pre>
   *
   * <code>string dataset_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for datasetId.
   */
  com.google.protobuf.ByteString getDatasetIdBytes();

  /**
   *
   *
   * <pre>
   * Only applicable to Datasets that have DataItems and Annotations.
   * A filter on Annotations of the Dataset. Only Annotations that both
   * match this filter and belong to DataItems not ignored by the split method
   * are used in respectively training, validation or test role, depending on
   * the role of the DataItem they are on (for the auto-assigned that role is
   * decided by AI Platform). A filter with same syntax as the one used in
   * [ListAnnotations][google.cloud.aiplatform.v1alpha1.DatasetService.ListAnnotations] may be used, but note
   * here it filters across all Annotations of the Dataset, and not just within
   * a single DataItem.
   * </pre>
   *
   * <code>string annotations_filter = 6;</code>
   *
   * @return The annotationsFilter.
   */
  java.lang.String getAnnotationsFilter();
  /**
   *
   *
   * <pre>
   * Only applicable to Datasets that have DataItems and Annotations.
   * A filter on Annotations of the Dataset. Only Annotations that both
   * match this filter and belong to DataItems not ignored by the split method
   * are used in respectively training, validation or test role, depending on
   * the role of the DataItem they are on (for the auto-assigned that role is
   * decided by AI Platform). A filter with same syntax as the one used in
   * [ListAnnotations][google.cloud.aiplatform.v1alpha1.DatasetService.ListAnnotations] may be used, but note
   * here it filters across all Annotations of the Dataset, and not just within
   * a single DataItem.
   * </pre>
   *
   * <code>string annotations_filter = 6;</code>
   *
   * @return The bytes for annotationsFilter.
   */
  com.google.protobuf.ByteString getAnnotationsFilterBytes();

  public com.google.cloud.aiplatform.v1alpha1.InputDataConfig.SplitCase getSplitCase();
}
