/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/job_state.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class JobStateProto {
  private JobStateProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n0google/cloud/aiplatform/v1alpha1/job_s"
          + "tate.proto\022 google.cloud.aiplatform.v1al"
          + "pha1\032\034google/api/annotations.proto*\341\001\n\010J"
          + "obState\022\031\n\025JOB_STATE_UNSPECIFIED\020\000\022\024\n\020JO"
          + "B_STATE_QUEUED\020\001\022\025\n\021JOB_STATE_PENDING\020\002\022"
          + "\025\n\021JOB_STATE_RUNNING\020\003\022\027\n\023JOB_STATE_SUCC"
          + "EEDED\020\004\022\024\n\020JOB_STATE_FAILED\020\005\022\030\n\024JOB_STA"
          + "TE_CANCELLING\020\006\022\027\n\023JOB_STATE_CANCELLED\020\007"
          + "\022\024\n\020JOB_STATE_PAUSED\020\010B\203\001\n$com.google.cl"
          + "oud.aiplatform.v1alpha1B\rJobStateProtoP\001"
          + "ZJgoogle.golang.org/genproto/googleapis/"
          + "cloud/aiplatform/v1alpha1;aiplatformb\006pr"
          + "oto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
