/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/model.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class ModelProto {
  private ModelProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Model_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Model_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Model_ExportFormat_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Model_ExportFormat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Model_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Model_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_PredictSchemata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_PredictSchemata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ModelContainerSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ModelContainerSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_EnvVar_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_EnvVar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Port_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Port_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n,google/cloud/aiplatform/v1alpha1/model"
          + ".proto\022 google.cloud.aiplatform.v1alpha1"
          + "\032\037google/api/field_behavior.proto\032\031googl"
          + "e/api/resource.proto\032.google/cloud/aipla"
          + "tform/v1alpha1/dataset.proto\0329google/clo"
          + "ud/aiplatform/v1alpha1/deployed_model_re"
          + "f.proto\0322google/cloud/aiplatform/v1alpha"
          + "1/explanation.proto\032\034google/protobuf/str"
          + "uct.proto\032\037google/protobuf/timestamp.pro"
          + "to\032\034google/api/annotations.proto\"\317\n\n\005Mod"
          + "el\022\014\n\004name\030\001 \001(\t\022\031\n\014display_name\030\002 \001(\tB\003"
          + "\340A\002\022\023\n\013description\030\003 \001(\t\022K\n\020predict_sche"
          + "mata\030\004 \001(\01321.google.cloud.aiplatform.v1a"
          + "lpha1.PredictSchemata\022 \n\023metadata_schema"
          + "_uri\030\005 \001(\tB\003\340A\005\022-\n\010metadata\030\006 \001(\0132\026.goog"
          + "le.protobuf.ValueB\003\340A\005\022[\n\030supported_expo"
          + "rt_formats\030\024 \003(\01324.google.cloud.aiplatfo"
          + "rm.v1alpha1.Model.ExportFormatB\003\340A\003\022J\n\021t"
          + "raining_pipeline\030\007 \001(\tB/\372A,\n*aiplatform."
          + "googleapis.com/TrainingPipeline\022Q\n\016conta"
          + "iner_spec\030\t \001(\01324.google.cloud.aiplatfor"
          + "m.v1alpha1.ModelContainerSpecB\003\340A\004\022\031\n\014ar"
          + "tifact_uri\030\032 \001(\tB\003\340A\005\022r\n$supported_deplo"
          + "yment_resources_types\030\n \003(\0162?.google.clo"
          + "ud.aiplatform.v1alpha1.Model.DeploymentR"
          + "esourcesTypeB\003\340A\003\022,\n\037supported_input_sto"
          + "rage_formats\030\013 \003(\tB\003\340A\003\022-\n supported_out"
          + "put_storage_formats\030\014 \003(\tB\003\340A\003\0224\n\013create"
          + "_time\030\r \001(\0132\032.google.protobuf.TimestampB"
          + "\003\340A\003\0224\n\013update_time\030\016 \001(\0132\032.google.proto"
          + "buf.TimestampB\003\340A\003\022P\n\017deployed_models\030\017 "
          + "\003(\01322.google.cloud.aiplatform.v1alpha1.D"
          + "eployedModelRefB\003\340A\003\022K\n\020explanation_spec"
          + "\030\027 \001(\01321.google.cloud.aiplatform.v1alpha"
          + "1.ExplanationSpec\022\014\n\004etag\030\020 \001(\t\022C\n\006label"
          + "s\030\021 \003(\01323.google.cloud.aiplatform.v1alph"
          + "a1.Model.LabelsEntry\032\037\n\014ExportFormat\022\017\n\002"
          + "id\030\001 \001(\tB\003\340A\003\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001("
          + "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"v\n\027DeploymentResour"
          + "cesType\022)\n%DEPLOYMENT_RESOURCES_TYPE_UNS"
          + "PECIFIED\020\000\022\027\n\023DEDICATED_RESOURCES\020\001\022\027\n\023A"
          + "UTOMATIC_RESOURCES\020\002:\\\352AY\n\037aiplatform.go"
          + "ogleapis.com/Model\0226projects/{project}/l"
          + "ocations/{location}/models/{model}\"{\n\017Pr"
          + "edictSchemata\022 \n\023instance_schema_uri\030\001 \001"
          + "(\tB\003\340A\005\022\"\n\025parameters_schema_uri\030\002 \001(\tB\003"
          + "\340A\005\022\"\n\025prediction_schema_uri\030\003 \001(\tB\003\340A\005\""
          + "\207\002\n\022ModelContainerSpec\022\031\n\timage_uri\030\001 \001("
          + "\tB\006\340A\002\340A\005\022\024\n\007command\030\002 \003(\tB\003\340A\005\022\021\n\004args\030"
          + "\003 \003(\tB\003\340A\005\022:\n\003env\030\004 \003(\0132(.google.cloud.a"
          + "iplatform.v1alpha1.EnvVarB\003\340A\005\022:\n\005ports\030"
          + "\005 \003(\0132&.google.cloud.aiplatform.v1alpha1"
          + ".PortB\003\340A\005\022\032\n\rpredict_route\030\006 \001(\tB\003\340A\005\022\031"
          + "\n\014health_route\030\007 \001(\tB\003\340A\005\"*\n\006EnvVar\022\021\n\004n"
          + "ame\030\001 \001(\tB\003\340A\002\022\r\n\005value\030\002 \001(\t\"\036\n\004Port\022\026\n"
          + "\016container_port\030\003 \001(\005B\200\001\n$com.google.clo"
          + "ud.aiplatform.v1alpha1B\nModelProtoP\001ZJgo"
          + "ogle.golang.org/genproto/googleapis/clou"
          + "d/aiplatform/v1alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.DatasetProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.DeployedModelNameProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ExplanationProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Model_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Model_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Model_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "PredictSchemata",
              "MetadataSchemaUri",
              "Metadata",
              "SupportedExportFormats",
              "TrainingPipeline",
              "ContainerSpec",
              "ArtifactUri",
              "SupportedDeploymentResourcesTypes",
              "SupportedInputStorageFormats",
              "SupportedOutputStorageFormats",
              "CreateTime",
              "UpdateTime",
              "DeployedModels",
              "ExplanationSpec",
              "Etag",
              "Labels",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Model_ExportFormat_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Model_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Model_ExportFormat_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Model_ExportFormat_descriptor,
            new java.lang.String[] {
              "Id",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Model_LabelsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Model_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_Model_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Model_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_PredictSchemata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_PredictSchemata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_PredictSchemata_descriptor,
            new java.lang.String[] {
              "InstanceSchemaUri", "ParametersSchemaUri", "PredictionSchemaUri",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ModelContainerSpec_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_ModelContainerSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ModelContainerSpec_descriptor,
            new java.lang.String[] {
              "ImageUri", "Command", "Args", "Env", "Ports", "PredictRoute", "HealthRoute",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_EnvVar_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_EnvVar_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_EnvVar_descriptor,
            new java.lang.String[] {
              "Name", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Port_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1alpha1_Port_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Port_descriptor,
            new java.lang.String[] {
              "ContainerPort",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.DatasetProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.DeployedModelNameProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ExplanationProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
