/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/model_service.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class ModelServiceProto {
  private ModelServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_UploadModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_DeleteModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_OutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_OutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_OutputInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_OutputInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationSliceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationSliceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_OutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_OutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_OutputInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_OutputInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n4google/cloud/aiplatform/v1alpha1/model"
          + "_service.proto\022 google.cloud.aiplatform."
          + "v1alpha1\032\034google/api/annotations.proto\032\027"
          + "google/api/client.proto\032\037google/api/fiel"
          + "d_behavior.proto\032\031google/api/resource.pr"
          + "oto\032)google/cloud/aiplatform/v1alpha1/io"
          + ".proto\032,google/cloud/aiplatform/v1alpha1"
          + "/model.proto\0327google/cloud/aiplatform/v1"
          + "alpha1/model_evaluation.proto\032=google/cl"
          + "oud/aiplatform/v1alpha1/model_evaluation"
          + "_slice.proto\0320google/cloud/aiplatform/v1"
          + "alpha1/operation.proto\032#google/longrunni"
          + "ng/operations.proto\032 google/protobuf/fie"
          + "ld_mask.proto\"\214\001\n\022UploadModelRequest\0229\n\006"
          + "parent\030\001 \001(\tB)\340A\002\372A#\n!locations.googleap"
          + "is.com/Location\022;\n\005model\030\002 \001(\0132\'.google."
          + "cloud.aiplatform.v1alpha1.ModelB\003\340A\002\"t\n\034"
          + "UploadModelOperationMetadata\022T\n\020generic_"
          + "metadata\030\001 \001(\0132:.google.cloud.aiplatform"
          + ".v1alpha1.GenericOperationMetadata\"J\n\023Up"
          + "loadModelResponse\0223\n\005model\030\001 \001(\tB$\372A!\n\037a"
          + "iplatform.googleapis.com/Model\"H\n\017GetMod"
          + "elRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037aiplatf"
          + "orm.googleapis.com/Model\"\264\001\n\021ListModelsR"
          + "equest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!location"
          + "s.googleapis.com/Location\022\016\n\006filter\030\002 \001("
          + "\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t"
          + "\022-\n\tread_mask\030\005 \001(\0132\032.google.protobuf.Fi"
          + "eldMask\"f\n\022ListModelsResponse\0227\n\006models\030"
          + "\001 \003(\0132\'.google.cloud.aiplatform.v1alpha1"
          + ".Model\022\027\n\017next_page_token\030\002 \001(\t\"K\n\022Delet"
          + "eModelRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037aip"
          + "latform.googleapis.com/Model\"\237\002\n\022ExportM"
          + "odelRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037aipla"
          + "tform.googleapis.com/Model\022]\n\routput_con"
          + "fig\030\002 \001(\0132A.google.cloud.aiplatform.v1al"
          + "pha1.ExportModelRequest.OutputConfigB\003\340A"
          + "\002\032s\n\014OutputConfig\022\030\n\020export_format_id\030\001 "
          + "\001(\t\022I\n\017gcs_destination\030\002 \001(\01320.google.cl"
          + "oud.aiplatform.v1alpha1.GcsDestination\"\212"
          + "\002\n\034ExportModelOperationMetadata\022T\n\020gener"
          + "ic_metadata\030\001 \001(\0132:.google.cloud.aiplatf"
          + "orm.v1alpha1.GenericOperationMetadata\022c\n"
          + "\013output_info\030\002 \001(\0132I.google.cloud.aiplat"
          + "form.v1alpha1.ExportModelOperationMetada"
          + "ta.OutputInfoB\003\340A\003\032/\n\nOutputInfo\022!\n\024gcs_"
          + "output_directory\030\001 \001(\tB\003\340A\003\"\025\n\023ExportMod"
          + "elResponse\"\\\n\031GetModelEvaluationRequest\022"
          + "?\n\004name\030\001 \001(\tB1\340A\002\372A+\n)aiplatform.google"
          + "apis.com/ModelEvaluation\"\276\001\n\033ListModelEv"
          + "aluationsRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#"
          + "\n!locations.googleapis.com/Location\022\016\n\006f"
          + "ilter\030\002 \001(\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_t"
          + "oken\030\004 \001(\t\022-\n\tread_mask\030\005 \001(\0132\032.google.p"
          + "rotobuf.FieldMask\"\205\001\n\034ListModelEvaluatio"
          + "nsResponse\022L\n\021model_evaluations\030\001 \003(\01321."
          + "google.cloud.aiplatform.v1alpha1.ModelEv"
          + "aluation\022\027\n\017next_page_token\030\002 \001(\t\"f\n\036Get"
          + "ModelEvaluationSliceRequest\022D\n\004name\030\001 \001("
          + "\tB6\340A\002\372A0\n.aiplatform.googleapis.com/Mod"
          + "elEvaluationSlice\"\313\001\n ListModelEvaluatio"
          + "nSlicesRequest\022A\n\006parent\030\001 \001(\tB1\340A\002\372A+\n)"
          + "aiplatform.googleapis.com/ModelEvaluatio"
          + "n\022\016\n\006filter\030\002 \001(\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\n"
          + "page_token\030\004 \001(\t\022-\n\tread_mask\030\005 \001(\0132\032.go"
          + "ogle.protobuf.FieldMask\"\225\001\n!ListModelEva"
          + "luationSlicesResponse\022W\n\027model_evaluatio"
          + "n_slices\030\001 \003(\01326.google.cloud.aiplatform"
          + ".v1alpha1.ModelEvaluationSlice\022\027\n\017next_p"
          + "age_token\030\002 \001(\t\"\304\002\n\037ExportEvaluatedDataI"
          + "temsRequest\022K\n\020model_evaluation\030\001 \001(\tB1\340"
          + "A\002\372A+\n)aiplatform.googleapis.com/ModelEv"
          + "aluation\022j\n\routput_config\030\002 \001(\0132N.google"
          + ".cloud.aiplatform.v1alpha1.ExportEvaluat"
          + "edDataItemsRequest.OutputConfigB\003\340A\002\032h\n\014"
          + "OutputConfig\022X\n\024bigquery_destination\030\001 \001"
          + "(\01325.google.cloud.aiplatform.v1alpha1.Bi"
          + "gQueryDestinationB\003\340A\002\"\247\002\n)ExportEvaluat"
          + "edDataItemsOperationMetadata\022T\n\020generic_"
          + "metadata\030\001 \001(\0132:.google.cloud.aiplatform"
          + ".v1alpha1.GenericOperationMetadata\022p\n\013ou"
          + "tput_info\030\002 \001(\0132V.google.cloud.aiplatfor"
          + "m.v1alpha1.ExportEvaluatedDataItemsOpera"
          + "tionMetadata.OutputInfoB\003\340A\003\0322\n\nOutputIn"
          + "fo\022$\n\027bigquery_output_dataset\030\001 \001(\tB\003\340A\003"
          + "\"+\n)ExportEvaluatedDataItemsOperationRes"
          + "ponse2\213\023\n\014ModelService\022\354\001\n\013UploadModel\0224"
          + ".google.cloud.aiplatform.v1alpha1.Upload"
          + "ModelRequest\032\035.google.longrunning.Operat"
          + "ion\"\207\001\202\323\344\223\002<\"7/v1alpha1/{parent=projects"
          + "/*/locations/*}/models:upload:\001*\332A\014paren"
          + "t,model\312A3\n\023UploadModelResponse\022\034UploadM"
          + "odelOperationMetadata\022\247\001\n\010GetModel\0221.goo"
          + "gle.cloud.aiplatform.v1alpha1.GetModelRe"
          + "quest\032\'.google.cloud.aiplatform.v1alpha1"
          + ".Model\"?\202\323\344\223\0022\0220/v1alpha1/{name=projects"
          + "/*/locations/*/models/*}\332A\004name\022\272\001\n\nList"
          + "Models\0223.google.cloud.aiplatform.v1alpha"
          + "1.ListModelsRequest\0324.google.cloud.aipla"
          + "tform.v1alpha1.ListModelsResponse\"A\202\323\344\223\002"
          + "2\0220/v1alpha1/{parent=projects/*/location"
          + "s/*}/models\332A\006parent\022\326\001\n\013DeleteModel\0224.g"
          + "oogle.cloud.aiplatform.v1alpha1.DeleteMo"
          + "delRequest\032\035.google.longrunning.Operatio"
          + "n\"r\202\323\344\223\0022*0/v1alpha1/{name=projects/*/lo"
          + "cations/*/models/*}\332A\004name\312A0\n\025google.pr"
          + "otobuf.Empty\022\027DeleteOperationMetadata\022\362\001"
          + "\n\013ExportModel\0224.google.cloud.aiplatform."
          + "v1alpha1.ExportModelRequest\032\035.google.lon"
          + "grunning.Operation\"\215\001\202\323\344\223\002<\"7/v1alpha1/{"
          + "name=projects/*/locations/*/models/*}:ex"
          + "port:\001*\332A\022name,output_config\312A3\n\023ExportM"
          + "odelResponse\022\034ExportModelOperationMetada"
          + "ta\022\323\001\n\022GetModelEvaluation\022;.google.cloud"
          + ".aiplatform.v1alpha1.GetModelEvaluationR"
          + "equest\0321.google.cloud.aiplatform.v1alpha"
          + "1.ModelEvaluation\"M\202\323\344\223\002@\022>/v1alpha1/{na"
          + "me=projects/*/locations/*/models/*/evalu"
          + "ations/*}\332A\004name\022\346\001\n\024ListModelEvaluation"
          + "s\022=.google.cloud.aiplatform.v1alpha1.Lis"
          + "tModelEvaluationsRequest\032>.google.cloud."
          + "aiplatform.v1alpha1.ListModelEvaluations"
          + "Response\"O\202\323\344\223\002@\022>/v1alpha1/{parent=proj"
          + "ects/*/locations/*/models/*}/evaluations"
          + "\332A\006parent\022\353\001\n\027GetModelEvaluationSlice\022@."
          + "google.cloud.aiplatform.v1alpha1.GetMode"
          + "lEvaluationSliceRequest\0326.google.cloud.a"
          + "iplatform.v1alpha1.ModelEvaluationSlice\""
          + "V\202\323\344\223\002I\022G/v1alpha1/{name=projects/*/loca"
          + "tions/*/models/*/evaluations/*/slices/*}"
          + "\332A\004name\022\376\001\n\031ListModelEvaluationSlices\022B."
          + "google.cloud.aiplatform.v1alpha1.ListMod"
          + "elEvaluationSlicesRequest\032C.google.cloud"
          + ".aiplatform.v1alpha1.ListModelEvaluation"
          + "SlicesResponse\"X\202\323\344\223\002I\022G/v1alpha1/{paren"
          + "t=projects/*/locations/*/models/*/evalua"
          + "tions/*}/slices\332A\006parent\022\331\002\n\030ExportEvalu"
          + "atedDataItems\022A.google.cloud.aiplatform."
          + "v1alpha1.ExportEvaluatedDataItemsRequest"
          + "\032\035.google.longrunning.Operation\"\332\001\202\323\344\223\002h"
          + "\"c/v1alpha1/{model_evaluation=projects/*"
          + "/locations/*/models/*/evaluations/*}:exp"
          + "ortEvaluatedDataItems:\001*\332A\020model_evaluat"
          + "ion\312AV\n)ExportEvaluatedDataItemsOperatio"
          + "nResponse\022)ExportEvaluatedDataItemsOpera"
          + "tionMetadata\032M\312A\031aiplatform.googleapis.c"
          + "om\322A.https://www.googleapis.com/auth/clo"
          + "ud-platformB\207\001\n$com.google.cloud.aiplatf"
          + "orm.v1alpha1B\021ModelServiceProtoP\001ZJgoogl"
          + "e.golang.org/genproto/googleapis/cloud/a"
          + "iplatform/v1alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.IoProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ModelProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ModelEvaluationProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ModelEvaluationSliceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UploadModelRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Model",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UploadModelOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_UploadModelResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_UploadModelResponse_descriptor,
            new java.lang.String[] {
              "Model",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetModelRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelsRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelsResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelsResponse_descriptor,
            new java.lang.String[] {
              "Models", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_aiplatform_v1alpha1_DeleteModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_DeleteModelRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_descriptor,
            new java.lang.String[] {
              "Name", "OutputConfig",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_OutputConfig_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_OutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportModelRequest_OutputConfig_descriptor,
            new java.lang.String[] {
              "ExportFormatId", "GcsDestination",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata", "OutputInfo",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_OutputInfo_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_OutputInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportModelOperationMetadata_OutputInfo_descriptor,
            new java.lang.String[] {
              "GcsOutputDirectory",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelResponse_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportModelResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportModelResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationsResponse_descriptor,
            new java.lang.String[] {
              "ModelEvaluations", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationSliceRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationSliceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_GetModelEvaluationSliceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken", "ReadMask",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesResponse_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ListModelEvaluationSlicesResponse_descriptor,
            new java.lang.String[] {
              "ModelEvaluationSlices", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_descriptor,
            new java.lang.String[] {
              "ModelEvaluation", "OutputConfig",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_OutputConfig_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_OutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsRequest_OutputConfig_descriptor,
            new java.lang.String[] {
              "BigqueryDestination",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata", "OutputInfo",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_OutputInfo_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_OutputInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationMetadata_OutputInfo_descriptor,
            new java.lang.String[] {
              "BigqueryOutputDataset",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationResponse_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_ExportEvaluatedDataItemsOperationResponse_descriptor,
            new java.lang.String[] {});
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.IoProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ModelProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ModelEvaluationProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ModelEvaluationSliceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.OperationProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
