/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/study.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class StudyProto {
  private StudyProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Trial_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Trial_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Trial_Parameter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Trial_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_MetricSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_MetricSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DoubleValueSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DoubleValueSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_IntegerValueSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_IntegerValueSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_CategoricalValueSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_CategoricalValueSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DiscreteValueSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DiscreteValueSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Measurement_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Measurement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_Measurement_Metric_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_Measurement_Metric_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n,google/cloud/aiplatform/v1alpha1/study"
          + ".proto\022 google.cloud.aiplatform.v1alpha1"
          + "\032\037google/api/field_behavior.proto\032\031googl"
          + "e/api/resource.proto\032\036google/protobuf/du"
          + "ration.proto\032\034google/protobuf/struct.pro"
          + "to\032\037google/protobuf/timestamp.proto\032\034goo"
          + "gle/api/annotations.proto\"\232\004\n\005Trial\022\017\n\002i"
          + "d\030\002 \001(\tB\003\340A\003\022A\n\005state\030\003 \001(\0162-.google.clo"
          + "ud.aiplatform.v1alpha1.Trial.StateB\003\340A\003\022"
          + "J\n\nparameters\030\004 \003(\01321.google.cloud.aipla"
          + "tform.v1alpha1.Trial.ParameterB\003\340A\003\022M\n\021f"
          + "inal_measurement\030\005 \001(\0132-.google.cloud.ai"
          + "platform.v1alpha1.MeasurementB\003\340A\003\0223\n\nst"
          + "art_time\030\007 \001(\0132\032.google.protobuf.Timesta"
          + "mpB\003\340A\003\0221\n\010end_time\030\010 \001(\0132\032.google.proto"
          + "buf.TimestampB\003\340A\003\032R\n\tParameter\022\031\n\014param"
          + "eter_id\030\001 \001(\tB\003\340A\003\022*\n\005value\030\002 \001(\0132\026.goog"
          + "le.protobuf.ValueB\003\340A\003\"f\n\005State\022\025\n\021STATE"
          + "_UNSPECIFIED\020\000\022\r\n\tREQUESTED\020\001\022\n\n\006ACTIVE\020"
          + "\002\022\014\n\010STOPPING\020\003\022\r\n\tSUCCEEDED\020\004\022\016\n\nINFEAS"
          + "IBLE\020\005\"\235\013\n\tStudySpec\022L\n\007metrics\030\001 \003(\01326."
          + "google.cloud.aiplatform.v1alpha1.StudySp"
          + "ec.MetricSpecB\003\340A\002\022R\n\nparameters\030\002 \003(\01329"
          + ".google.cloud.aiplatform.v1alpha1.StudyS"
          + "pec.ParameterSpecB\003\340A\002\022H\n\talgorithm\030\003 \001("
          + "\01625.google.cloud.aiplatform.v1alpha1.Stu"
          + "dySpec.Algorithm\032\273\001\n\nMetricSpec\022\026\n\tmetri"
          + "c_id\030\001 \001(\tB\003\340A\002\022R\n\004goal\030\002 \001(\0162?.google.c"
          + "loud.aiplatform.v1alpha1.StudySpec.Metri"
          + "cSpec.GoalTypeB\003\340A\002\"A\n\010GoalType\022\031\n\025GOAL_"
          + "TYPE_UNSPECIFIED\020\000\022\014\n\010MAXIMIZE\020\001\022\014\n\010MINI"
          + "MIZE\020\002\032\231\007\n\rParameterSpec\022f\n\021double_value"
          + "_spec\030\002 \001(\0132I.google.cloud.aiplatform.v1"
          + "alpha1.StudySpec.ParameterSpec.DoubleVal"
          + "ueSpecH\000\022h\n\022integer_value_spec\030\003 \001(\0132J.g"
          + "oogle.cloud.aiplatform.v1alpha1.StudySpe"
          + "c.ParameterSpec.IntegerValueSpecH\000\022p\n\026ca"
          + "tegorical_value_spec\030\004 \001(\0132N.google.clou"
          + "d.aiplatform.v1alpha1.StudySpec.Paramete"
          + "rSpec.CategoricalValueSpecH\000\022j\n\023discrete"
          + "_value_spec\030\005 \001(\0132K.google.cloud.aiplatf"
          + "orm.v1alpha1.StudySpec.ParameterSpec.Dis"
          + "creteValueSpecH\000\022\031\n\014parameter_id\030\001 \001(\tB\003"
          + "\340A\002\022W\n\nscale_type\030\006 \001(\0162C.google.cloud.a"
          + "iplatform.v1alpha1.StudySpec.ParameterSp"
          + "ec.ScaleType\032A\n\017DoubleValueSpec\022\026\n\tmin_v"
          + "alue\030\001 \001(\001B\003\340A\002\022\026\n\tmax_value\030\002 \001(\001B\003\340A\002\032"
          + "B\n\020IntegerValueSpec\022\026\n\tmin_value\030\001 \001(\003B\003"
          + "\340A\002\022\026\n\tmax_value\030\002 \001(\003B\003\340A\002\032+\n\024Categoric"
          + "alValueSpec\022\023\n\006values\030\001 \003(\tB\003\340A\002\032(\n\021Disc"
          + "reteValueSpec\022\023\n\006values\030\001 \003(\001B\003\340A\002\"n\n\tSc"
          + "aleType\022\032\n\026SCALE_TYPE_UNSPECIFIED\020\000\022\025\n\021U"
          + "NIT_LINEAR_SCALE\020\001\022\022\n\016UNIT_LOG_SCALE\020\002\022\032"
          + "\n\026UNIT_REVERSE_LOG_SCALE\020\003B\026\n\024parameter_"
          + "value_spec\"J\n\tAlgorithm\022\031\n\025ALGORITHM_UNS"
          + "PECIFIED\020\000\022\017\n\013GRID_SEARCH\020\002\022\021\n\rRANDOM_SE"
          + "ARCH\020\003\"\250\001\n\013Measurement\022\027\n\nstep_count\030\002 \001"
          + "(\003B\003\340A\003\022J\n\007metrics\030\003 \003(\01324.google.cloud."
          + "aiplatform.v1alpha1.Measurement.MetricB\003"
          + "\340A\003\0324\n\006Metric\022\026\n\tmetric_id\030\001 \001(\tB\003\340A\003\022\022\n"
          + "\005value\030\002 \001(\001B\003\340A\003B\200\001\n$com.google.cloud.a"
          + "iplatform.v1alpha1B\nStudyProtoP\001ZJgoogle"
          + ".golang.org/genproto/googleapis/cloud/ai"
          + "platform/v1alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Trial_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Trial_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Trial_descriptor,
            new java.lang.String[] {
              "Id", "State", "Parameters", "FinalMeasurement", "StartTime", "EndTime",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Trial_Parameter_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Trial_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Trial_Parameter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Trial_Parameter_descriptor,
            new java.lang.String[] {
              "ParameterId", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_descriptor,
            new java.lang.String[] {
              "Metrics", "Parameters", "Algorithm",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_MetricSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_MetricSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_MetricSpec_descriptor,
            new java.lang.String[] {
              "MetricId", "Goal",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor,
            new java.lang.String[] {
              "DoubleValueSpec",
              "IntegerValueSpec",
              "CategoricalValueSpec",
              "DiscreteValueSpec",
              "ParameterId",
              "ScaleType",
              "ParameterValueSpec",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DoubleValueSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DoubleValueSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DoubleValueSpec_descriptor,
            new java.lang.String[] {
              "MinValue", "MaxValue",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_IntegerValueSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_IntegerValueSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_IntegerValueSpec_descriptor,
            new java.lang.String[] {
              "MinValue", "MaxValue",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_CategoricalValueSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_CategoricalValueSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_CategoricalValueSpec_descriptor,
            new java.lang.String[] {
              "Values",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DiscreteValueSpec_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DiscreteValueSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_StudySpec_ParameterSpec_DiscreteValueSpec_descriptor,
            new java.lang.String[] {
              "Values",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Measurement_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_Measurement_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Measurement_descriptor,
            new java.lang.String[] {
              "StepCount", "Metrics",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_Measurement_Metric_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_Measurement_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_Measurement_Metric_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_Measurement_Metric_descriptor,
            new java.lang.String[] {
              "MetricId", "Value",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
