/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1alpha1/training_pipeline.proto

package com.google.cloud.aiplatform.v1alpha1;

public final class TrainingPipelineProto {
  private TrainingPipelineProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_InputDataConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_InputDataConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_FractionSplit_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_FractionSplit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_FilterSplit_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_FilterSplit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_PredefinedSplit_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_PredefinedSplit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1alpha1_TimestampSplit_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1alpha1_TimestampSplit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n8google/cloud/aiplatform/v1alpha1/train"
          + "ing_pipeline.proto\022 google.cloud.aiplatf"
          + "orm.v1alpha1\032\037google/api/field_behavior."
          + "proto\032\031google/api/resource.proto\032,google"
          + "/cloud/aiplatform/v1alpha1/model.proto\0325"
          + "google/cloud/aiplatform/v1alpha1/pipelin"
          + "e_state.proto\032\034google/protobuf/struct.pr"
          + "oto\032\037google/protobuf/timestamp.proto\032\027go"
          + "ogle/rpc/status.proto\032\034google/api/annota"
          + "tions.proto\"\257\007\n\020TrainingPipeline\022\021\n\004name"
          + "\030\001 \001(\tB\003\340A\003\022\031\n\014display_name\030\002 \001(\tB\003\340A\002\022L"
          + "\n\021input_data_config\030\003 \001(\01321.google.cloud"
          + ".aiplatform.v1alpha1.InputDataConfig\022%\n\030"
          + "training_task_definition\030\004 \001(\tB\003\340A\002\0229\n\024t"
          + "raining_task_inputs\030\005 \001(\0132\026.google.proto"
          + "buf.ValueB\003\340A\002\022;\n\026training_task_metadata"
          + "\030\006 \001(\0132\026.google.protobuf.ValueB\003\340A\003\022@\n\017m"
          + "odel_to_upload\030\007 \001(\0132\'.google.cloud.aipl"
          + "atform.v1alpha1.Model\022C\n\005state\030\t \001(\0162/.g"
          + "oogle.cloud.aiplatform.v1alpha1.Pipeline"
          + "StateB\003\340A\003\022&\n\005error\030\n \001(\0132\022.google.rpc.S"
          + "tatusB\003\340A\003\0224\n\013create_time\030\013 \001(\0132\032.google"
          + ".protobuf.TimestampB\003\340A\003\0223\n\nstart_time\030\014"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\r \001(\0132\032.google.protobuf.Timest"
          + "ampB\003\340A\003\0224\n\013update_time\030\016 \001(\0132\032.google.p"
          + "rotobuf.TimestampB\003\340A\003\022N\n\006labels\030\017 \003(\0132>"
          + ".google.cloud.aiplatform.v1alpha1.Traini"
          + "ngPipeline.LabelsEntry\032-\n\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:~\352A{\n*aipl"
          + "atform.googleapis.com/TrainingPipeline\022M"
          + "projects/{project}/locations/{location}/"
          + "trainingPipelines/{training_pipeline}\"\375\002"
          + "\n\017InputDataConfig\022I\n\016fraction_split\030\002 \001("
          + "\0132/.google.cloud.aiplatform.v1alpha1.Fra"
          + "ctionSplitH\000\022E\n\014filter_split\030\003 \001(\0132-.goo"
          + "gle.cloud.aiplatform.v1alpha1.FilterSpli"
          + "tH\000\022M\n\020predefined_split\030\004 \001(\01321.google.c"
          + "loud.aiplatform.v1alpha1.PredefinedSplit"
          + "H\000\022K\n\017timestamp_split\030\005 \001(\01320.google.clo"
          + "ud.aiplatform.v1alpha1.TimestampSplitH\000\022"
          + "\027\n\ndataset_id\030\001 \001(\tB\003\340A\002\022\032\n\022annotations_"
          + "filter\030\006 \001(\tB\007\n\005split\"^\n\rFractionSplit\022\031"
          + "\n\021training_fraction\030\001 \001(\001\022\033\n\023validation_"
          + "fraction\030\002 \001(\001\022\025\n\rtest_fraction\030\003 \001(\001\"V\n"
          + "\013FilterSplit\022\027\n\017training_filter\030\001 \001(\t\022\031\n"
          + "\021validation_filter\030\002 \001(\t\022\023\n\013test_filter\030"
          + "\003 \001(\t\"#\n\017PredefinedSplit\022\020\n\003key\030\001 \001(\tB\003\340"
          + "A\002\"q\n\016TimestampSplit\022\031\n\021training_fractio"
          + "n\030\001 \001(\001\022\033\n\023validation_fraction\030\002 \001(\001\022\025\n\r"
          + "test_fraction\030\003 \001(\001\022\020\n\003key\030\004 \001(\tB\003\340A\002B\213\001"
          + "\n$com.google.cloud.aiplatform.v1alpha1B\025"
          + "TrainingPipelineProtoP\001ZJgoogle.golang.o"
          + "rg/genproto/googleapis/cloud/aiplatform/"
          + "v1alpha1;aiplatformb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.ModelProto.getDescriptor(),
              com.google.cloud.aiplatform.v1alpha1.PipelineStateProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "InputDataConfig",
              "TrainingTaskDefinition",
              "TrainingTaskInputs",
              "TrainingTaskMetadata",
              "ModelToUpload",
              "State",
              "Error",
              "CreateTime",
              "StartTime",
              "EndTime",
              "UpdateTime",
              "Labels",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_LabelsEntry_descriptor =
        internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_TrainingPipeline_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_InputDataConfig_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1alpha1_InputDataConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_InputDataConfig_descriptor,
            new java.lang.String[] {
              "FractionSplit",
              "FilterSplit",
              "PredefinedSplit",
              "TimestampSplit",
              "DatasetId",
              "AnnotationsFilter",
              "Split",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_FractionSplit_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1alpha1_FractionSplit_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_FractionSplit_descriptor,
            new java.lang.String[] {
              "TrainingFraction", "ValidationFraction", "TestFraction",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_FilterSplit_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1alpha1_FilterSplit_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_FilterSplit_descriptor,
            new java.lang.String[] {
              "TrainingFilter", "ValidationFilter", "TestFilter",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_PredefinedSplit_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1alpha1_PredefinedSplit_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_PredefinedSplit_descriptor,
            new java.lang.String[] {
              "Key",
            });
    internal_static_google_cloud_aiplatform_v1alpha1_TimestampSplit_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_aiplatform_v1alpha1_TimestampSplit_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1alpha1_TimestampSplit_descriptor,
            new java.lang.String[] {
              "TrainingFraction", "ValidationFraction", "TestFraction", "Key",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.ModelProto.getDescriptor();
    com.google.cloud.aiplatform.v1alpha1.PipelineStateProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
